### ISSUE TITLE
Relationship to IndieUI: Events 1.0

### ISSUE THREAD

**Issue by AFBarstow** [w3c/editing#1]
Hi Ben - I just started reading the explainer doc (BTW, it's really nice to have this!), and I was wondering -> what, if any, relationship is there between what the explainer calls "Intention Events" and the IndieUI: Events 1.0 spec. If these concepts are orthogonal, then just close/delete this issue; otherwise, perhaps it would be helpful to include a sentence or two about the relationship.

(FYI, some history here is http://lists.w3.org/Archives/Public/public-webapps/2014AprJun/0806.html).

**Comment by BenjamP** [comment]
Added a paragraph about this. We should engage with the IndieUI folks as soon as we have a mailing list set up.
