### ISSUE TITLE
The Ranges type is not defined, should be FrozenArray<Range>?

### ISSUE THREAD

**Issue by foolip** [w3c/editing#113]
https://w3c.github.io/editing/input-events.html#widl-InputEvent-targetRanges

DOM has `Range` only: https://dom.spec.whatwg.org/#interface-range

@annevk

**Comment by johanneswilm** [comment]
See https://discourse.wicg.io/t/proposal-staticrange-to-be-used-instead-of-range-for-new-apis/1472
