### ISSUE TITLE
"beforeinput"/"beforeInput" naming clarification

### ISSUE THREAD

**Issue by chong-z** [w3c/editing#116]
http://w3c.github.io/editing/input-events.html#event-type-beforeinput is showing the name as all lower cases `beforeinput`, but other places are showing it as camelCase `beforeInput`.

So which one should `addEventListener(...)` use?

**Comment by johanneswilm** [comment]
"beforeinput" is what is used in the ui-events spec as well [1], so that must be correct.

[1] https://w3c.github.io/uievents/

**Comment by garykac** [comment]
It should be all lowercase.

As some point "beforeInput" was considered because it matched the proposed "textInput", but that's no longer an issue and event names should be all lowercase.

**Comment by johanneswilm** [comment]
It should be changed to lowercase everywhere now.

**Comment by chong-z** [comment]
I'm not sure if I should fire a separate issue in uievents but https://cdn.rawgit.com/w3c/uievents/gh-pages/tools/key-event-viewer.html is still using `beforeInput`
`Line 45: addEventListener(input, "beforeInput", onBeforeInput);`

**Comment by garykac** [comment]
I fixed that earlier today (prompted by this bug).
https://github.com/w3c/uievents/commit/012c59b6b1dc478f5b3ba0a86b91c557a3aef732

If you see any other issues, then please file a bug in uievents
