### ISSUE TITLE
beforeInput: Rename "inputCharacter" to "inputText"

### ISSUE THREAD

**Issue by yosinch** [w3c/editing#119]
One user action can insert multiple characters instead of one character. "Character" suffix mislead web authors.

**Comment by chong-z** [comment]
Agree that using `insertText` is better since it's a more standard command name defined in https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand#Commands. (See discussion in #79 for the list of `inputType` to start with)

**Comment by johanneswilm** [comment]
Hey, @choniong , I couldn't merge your PR due to some restriction set in the W3C's github group, but I made the change nevertheless, as there didn't seem to be any opposition.
