### ISSUE TITLE
[Input Events] Rename "replaceContent" with "insertContent" or "insertNonText"

### ISSUE THREAD

**Issue by chong-z** [w3c/editing#126]
Accord to discussion in https://github.com/w3c/editing/issues/124#issuecomment-214480492 it would have a better clarity if we could rename "replaceContent" with "insertContent" or "insertNonText".

**Comment by johanneswilm** [comment]
I would favor insertNonText. So far it seems noone opposes that term. Unless someone opposes the term, I think we should change it shortly.

**Comment by johanneswilm** [comment]
If we are to use the terminology used in execCommand whenever possible, how about using "insertHTML"? (not sure if HTML quite covers it. The DOM can contain things one cannot express in HTML)

**Comment by ayg** [comment]
insertHTML in execCommand is used for inserting an opaque author-provided piece of HTML.  I don't think it's similar to this.

insertNonText suggests to me that it cannot be text, but if this is meant to be used for spellcheck, it can be simple text, right?

From an author perspective, is there any reason these two input types should actually be separate?  Maybe it would make more sense to have a generic insertContent event that fires for any type of content insertion, and scripts could inspect .data to see what the change is.  targetRanges would be null for an insertion, and non-null for a replacement.  If authors want to know the method of insertion, additional properties could be exposed.  But inserting a word by dragging vs. by saying it seems like a subtle distinction, and I'm not sure why we need two input types.

**Comment by johanneswilm** [comment]
@ayg The difference is that one will want to treat keyboard/IME input into textnodes or newly created textnodes in one way, and complex HTML changes that come from other places in another way. See also https://github.com/w3c/editing/issues/124#issuecomment-211944715.
