### ISSUE TITLE
New API: Selection#makeVisible()

### ISSUE THREAD

**Issue by yosinch** [w3c/editing#129]
I would like to propose new selection API, Selection#makeVisible() which makes caret(extentNode, extenOffset) visible in viewport.

Background:
It is hard to make caret visible, if it is in a element with "overflow: scroll" CSS property. Or, there is no way for TEXTAREA.

Inspired by http://crbug.com/612729

**Comment by rniwa** [comment]
What do you mean by "visible"?  Are you talking about scrolling the viewport / scrollable element so that the caret is visible in the screen?

**Comment by rniwa** [comment]
By the way, this is in the right issue tracker.  Please file it in https://github.com/w3c/selection-api/issues instead.

**Comment by johanneswilm** [comment]
As this is related to the selection and it wouldn't change the DOM, as far as I understand it, I agree with @rniwa that this should probably be filed with the Selection API. @yosinch can we agree on moving it there?

**Comment by gked** [comment]
@yosinch: I took the liberty of moving your request into selection issue tracker [here.](https://github.com/w3c/selection-api/issues/73).

**Comment by johanneswilm** [comment]
@gked: Thanks!
