### ISSUE TITLE
inputType for Menu Bar>Edit>Delete (no obvious direction)

### ISSUE THREAD

**Issue by chong-z** [w3c/editing#130]
Should we add a new inputType (`DeleteContent/Selection/?`) since there is no obvious direction?

e.g. On Mac it will delete selection, and do nothing if collapsed.
(On other platforms the classic Menu Bar is not always shown.)

Also Note:
Menu Bar delete also acts as `Kill` on Mac, so later you can `Yank` by `Ctrl+y`.
I'm not sure if we should add new types, or can we just use `Delete*` and `Insert*`?

**Comment by johanneswilm** [comment]
That is an interesting question. On the one hans, you are right that there is no direction given and that would be an argument for creating a directionless option.

On the other hand, the direction always needs to be something (forward or backward), so the JavaScript define actions for backward and another for forward. My guess is that the directionless mode will be bundled together with the backward deletion -- but some apps may choose to have it go the other way. I don't know if that is really what the Mac OS X developers envision: that their built-in menus will cause quite different things, depending on how the JavaScript authors decide.

**Comment by johanneswilm** [comment]
This issue was moved to w3c/input-events#25
