### ISSUE TITLE
Should we expose physical direction in Deletion commands? (for the case of RTL)

### ISSUE THREAD

**Issue by chong-z** [w3c/editing#133]
I'm not so familiar with RTL language issues, but it seems that we are currently only exposing logical directions (`Delete*Forward/Backward`).

So will it be difficult for JS to make use of these information without knowing the actual direction (`Up/Down/Left/Right`)?

Here is a `vertical-rl` example where `DeleteBackward` means `DeleteUpward`: https://jsbin.com/yusocu

**Comment by johanneswilm** [comment]
@choniong Logical directions are generally more important when writing editor code. To handle a `Delete*Backward` we just need to know where in the DOM-tree the selection currently is and then change what is before it in the DOM-tree without having to worry about what direction the text is rendered in on the screen.

There may also be cases where it's of interest what physical direction the deletion/insertion occurs in, but all I can think about are cases where one is trying to place a DOM-based caret using JavaScript, but even then when can simply find the coordinates of the selection after the deletion and draw the caret there.

Can you think of circumstances where this would be important?

**Comment by chong-z** [comment]
Thanks for the prompt reply! That sounds good. I don't have such circumstances in mind though, but @yosinch mentioned one about `vertical-rl` that I couldn't fully understand/reproduce (the `Forward-Line == Left-Line` case), CCing @yosinch for more info.

> Example: writing-mode: vertical-rl (Japanese books use this)
> - Forward-Character == Down Character
> - Backward-Character == Up Character
> - Forward-Line == Left-Line
> - Backward-Line == Right-Line

**Comment by johanneswilm** [comment]
> @yosinch mentioned one about `vertical-rl` that I couldn't fully understand/reproduce (the `Forward-Line == Left-Line` case)

It would be interested to hear what that is about. For deleting a line forward or backward, in JS I would use the `getTargetRanges` method to find what part of the DOM corresponds to the line that is to be deleted forward or backward. For the most basic case it seems like it wouldn't matter which direction the lines are rendered on-screen.

**Comment by yosinch** [comment]
Deletion should have logical direction  (forward and backward) and granularity (character, word, line, ...).
Default behavior of "keyDown" event might generate beforeinput event with deletion type based on key code and modifies.

**Comment by johanneswilm** [comment]
> Deletion should have logical direction (forward and backward) and granularity (character, word, line, ...).

Just the way it is setup already right now, correct?

> Default behavior of "keyDown" event might generate beforeinput event

Yes, this is described in the ui events [1], correct?

> with deletion type based on key code and modifies.

Right, basically the backspace-key gives a different deletion-direction than the delete-key. And for deletion of words and lines in either direction there are other shortcuts on some platforms. Right?

If we agree on all this, and the current spec draft already covers all of this, should we close this ticket? What do you guys think?

[1] https://w3c.github.io/uievents/#events-keyboard-event-order

**Comment by yosinch** [comment]
I agree all of them except for directional line deletion. 

AFAIK, there is no key binding for line deletion. So, it is hard to imagine what forward/backward deletion of line.

Do you define line deletion as below?
- `selection.modify('extend', direction, 'lineboundary')`
- `document.execCommand('delete')`

If so, forward delete remove characters between caret to end of line:
Where | is caret, ^ is anchor.

Forward line deletion:
  Before: `abc|def\n`
  After Extend: `abc^def|\n`
  After Delete: `abc\n`

Backward line deletion:
  Before: `abc|def\n`
  After Extend: `|abc^def\n`
  After Delete: `|def\n`

Note: Assume "lineboundary" exclude end-of-line marker, e.g. \n or BR

**Comment by johanneswilm** [comment]
I think you may be right. I believe we initially added line deletion because we believed there was at least one OS/browser combination that had this built-in. 

I agree with your definition, with two additions:
1. There should still be a caret after the selection in your first example:
   
   Instead of:
   
   > After Delete: abc\n
   
   it should end with
   
   > After Delete: |abc\n
2. There should also be a "lineboundary" whenever there is a softline break.

Do you think we should add this description to the spec? Maybe as an example?

**Comment by chong-z** [comment]
> AFAIK, there is no key binding for line deletion. So, it is hard to imagine what forward/backward deletion of line.

On macOS (Firefox, Chrome, Safari and native apps):
1. `command+delete` is `DeleteLineBackward`
   - On Chrome it maps to [`- deleteToBeginningOfLine:`](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSResponder_Class/#//apple_ref/occ/instm/NSResponder/deleteToBeginningOfLine:)
2. `control+k` is Emacs-style `Kill`
   - On Chrome it maps to [`- deleteToEndOfParagraph:`](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSResponder_Class/#//apple_ref/occ/instm/NSResponder/deleteToEndOfParagraph:) but actually acts like `DeleteLineForward` (e.g. It will stop on `<br>` instead of `</p>`, if I used it correctly)

I'm not sure about the implementation details on Firefox or Safari, but the behaviors are the same.

Also see discussion https://github.com/w3c/editing/issues/125#issuecomment-213054474

(note: `command+fn+delete` won't do `DeleteLineForward` for me)

**Comment by johanneswilm** [comment]
So for backward we can only delete the rest of the line and for forward only delete to the end of the paragraph? That seems a bit inconsistent. Could we standardize this in some way?

**Comment by yosinch** [comment]
From platform dev's view, it is easy to understand that Delete(G) = Extend Selection by G + Delete.
From user's view, it is also easy to understand since selected range will be delete.

So, current behavior of forward/backward deletion of line is logically make sense and it works as other granularity.

Only one exception is Backward Deletion regarding grapheme, some script want to remove grapheme, some script want to remove code point. [UAX#29 UNICODE TEXT SEGMENTATION,](http://www.unicode.org/reports/tr29/) doesn't define behavior for Backward Deletion.

So, I would like to have specification of backward deletion for grapheme.

**Comment by johanneswilm** [comment]
> So, I would like to have specification of backward deletion for grapheme.

I wonder how much this depends on the language? In German. Scandinavian, Spanish or Portuguese accents on letters, to me it would seem somewhat odd if the backspace key would just remove the accent but not the rest of the letter. I assume this is different in some other languages.

Or am I possibly misunderstanding you completely?

**Comment by yosinch** [comment]
For Latin language, it is natural to remove graheme once. But some languages aren't.

Here are examples:
Malayalam
http://crbug.com/47467  Backspace works "unintuitively" for complex scripts in some cases

Japanease
http://crbug.com/535673 Inconsistent behavior when deleting U+FF8A U+FF9E in a text area

**Comment by johanneswilm** [comment]
@yosinch Would it help if there was something like `deleteCodePointBackward`? Would the browser generally know whether the current script/language will ask fro deletion of grapheme or code point? Or would this be clear based on the target ranges (an empty range means likely that only a code point is to be deleted)?

This only has to do with `deleteContentForward` and `deleteContentBackward`, correct? Not deletion of words or lines, right?

**Comment by yosinch** [comment]
> Would it help if there was something like deleteCodePointBackward?
> In short, it makes world confusing. Backspace behavior depends on platform, it is hard to implement simulating platform behavior for every language.

Until JS proves function to deal graphme, e.g. like what Swift, we should not provide low level primitive.

> Would the browser generally know whether the current script/language will ask fro deletion of grapheme or code point?
> Yes, browser should know. Browsers implement UAX#29 with platform tailoring.
> 
> This only has to do with deleteContentForward and deleteContentBackward, correct? Not deletion of words or lines, right?
> Yes. But, I propose selection should be extend to both direction to cover grapheme. Deleting code point in grapheme makes user surprised, e.g. leave accent character in content.

**Comment by johanneswilm** [comment]
So what do you propose we do, @yosinch? If we don't want to give access to CodePoint deletion in JS, isn't the only option left to say that in all languages, outside of IME, we always delete the entire grapheme? Or is there another option?

> Until JS proves function to deal graphme, e.g. like what Swift, 

Could you try to rephrase that? I don't think I understood it.

**Edit:** I think I understood it now: As long JavaScript cannot manipulate characters at the CodePoint level, the way one can do with Swift, there is no point in showing such an intention.

To that I would say that we have to choose between one of these:

A) We determine that complete grapheme deletion is OK in all languages, including Malay/Japanese.

B) We add CodePoint manipulation functions to JavaScript.

C) We say that we only support scripts that behave like European languages.

D) We say that contenteditable should work on its own, without any help from JavaScript.

Whether A is OK for the time being -- I don't know, what do you think? C and D are definitely bad solutions. B will take more time. So maybe we have to say A for now and B ASAP?

**Comment by johanneswilm** [comment]
Btw, this started out as a question relation to physical directions and the beforeinput event. Now it seems to have shifted to a question of sub-character manipulation. Should we maybe close this ticket and create a new one for the new issue?

**Comment by yosinch** [comment]
I propose:
- Delete forward = delete grapheme
- Delete backward = delete grapheme or code point depends on language and platform

> > Until  JS proves function to deal graphme, e.g. like what Swift,
> > Could you try to rephrase that? I don't think I understood it.
> > In JS standard library, there are no functions to deal grapheme. 
> > When web devs want to implement "Delete Forward/Backward by Grapheme", they need to have library implementing UAX#29.

For "Delete Backward like Backsapce", web devs need to know platform convention about deleting one code point or grapheme by multiple code points.

Swift provides functions handling grapheme:
[Strings and Characters in Switf](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/StringsAndCharacters.html)

**Comment by johanneswilm** [comment]
> I propose:
> - Delete forward = delete grapheme
> - Delete backward = delete grapheme or code point depends on language and platform

Ok, but remember that the point with the beforeinput event is that the JavaScript can implement all the DOM changes itself and not rely on the browser for any of it. That's the most important point of the beforeinput event for many editors. So if delete backward is to mean code point deletion, but the JavaScript cannot know that this was meant and additionally doesn't have a simply way to remove a codepoint, then this will be broken for all the scripts that require this. So that doesn't seem like a good idea.

**Comment by johanneswilm** [comment]
Trying this out, it doesn't seem straightforward how to handle this in JavaScript.

```
> let a = "<b>\u{65}\u{301}</b>"
<b>é</b>
> a.length
8
```

What if the caret is here and the user asks for forward delete:

```
<b>|\u{65}\u{301}</b>
```

Or what if the caret is here, and the user asks for backward delete:

```
<b>\u{65}\u{301}|</b>
```

Without some knowledge of what those unicode characters correspond to, it seems difficult for the JavaScript to delete the right part of the DOM, right?

**Comment by frivoal** [comment]
Since Javascript is ultimately in charge here, it can do whatever it wants, and if there is fancy knowledge of unicode and/or any special intent, I can imagine various editors choosing to do different things (code points vs grapheme clusters, etc).

However, it would be good to make life easy for the JavaScript developer (and sane for the end users) by and providing data about what the browser would consider "one character" in that context, so that that can be used a default.

**Comment by johanneswilm** [comment]
Reading through the discussion that CKeditor has had about this that is linked to above, it sounds as if the trick for JavaScript-solutions is simply to have a hard coded list of what unicode characters correspond to base characters and which ones correspond to code points.

**Comment by johanneswilm** [comment]
Reading through the discussion that CKeditor has had about this that is linked to above, it sounds as if the trick for JavaScript-solutions is simply to have a hard coded list of what unicode characters correspond to base characters and which ones correspond to code points.

> However, it would be good to make life easy for the JavaScript developer (and sane for the end users) by and providing data about what the browser would consider "one character" in that context, so that that can be used a default.

I agree. However given that we have the target ranges, and that this is an issue only when doing a simple backward/forward deletion, I guess the target range for a forward simple deletion should point to the base character with all its codepoints, right? Then that should take away the complexity of that in the JS.

**Comment by kojiishi** [comment]
Could you clarify whether they map to Backspace/Delete keys, or you are talking about logical operations similar to what execCommand provides?

I think what@yosinch is saying is that browsers often have to do more intelligent things for Backspace to match to platforms behavior.

If what you're talking about is commands that deletes a grapheme, not a command that does what Backspace does, that may change the discussion.

Edit: fix typo

**Comment by johanneswilm** [comment]
I think this ticket has covered several different issues that shouldn't have ben in the same ticket. I also think we are close to resolving, in which case we can close this ticket entirely.

All the initial things mentioned about RTL languages, delete to end of line, etc. seem to have been resolved.

As for the remaining issue:

As I understand it, this is about the two commands `deleteContentsForward` and `deleteContentsBackward`. These actually don't specify whether we are talking about graphemes, codepoints, tables, images, non-editable regions, or whatever.

Given that every code point seems to increase the length of a string y 1 in JavaScript, it seems that the targetranges can point specifically to either just a single unicode character which corresponds to a codepoint, or a series of characters which correspond to a base character and all its associated codepoints. If this is so, then it seems that this issue solves itself as long as we make sure that the targetranges point to what the browser believes should be deleted.

> I think what@yosinch is saying is that browsers often have to do more intelligent things for Backspace to match to platforms behavior.

From my eperimenting with the string above, it seems that backspace actually is the easier operation, because one simply removes the last character without having to worry about what type it is. It is forward deletion that can be tricky, because the deletion of a base character also requires the deletion of all the associated codepoint characters.

**Comment by johanneswilm** [comment]
I read through the spec draft, and actually it looks like it's already sayign what needs to be said:
- deletion forward/backward doesn't say that it's only about graphemes
- getTargetRanges should already provide information about what is to be deleted according to the logic of the given browser

But I see that this may be something others may wonder about as well. I wonder therefore if we should:
1. Add the grapheme/codepoint thing on platform X as an example of what the targetRanges may return under specific circumstances.
2. More clearly list all the things that could be deleted after the two mentioned beforeinput events unless there is a non-collapsed selection (graphemes, codepoints, tables, non-editable areas, stub elements,  etc.). This list may become very large though.

**Comment by frivoal** [comment]
> it seems that the targetranges can point specifically to either just a single unicode character which corresponds to a codepoint, or a series of characters which correspond to a base character and all its associated codepoints. If this is so, then it seems that this issue solves itself as long as we make sure that the targetranges point to what the browser believes should be deleted.

Makes sense to me. JS is free to ignore that information, but it's there in case it wants to follow browser/platform conventions.

> it seems that backspace actually is the easier operation, because one simply removes the last character without having to worry about what type it is

I think that depends on the language. Which brings us back to exposing what the browser would delete, and letting JS figure out if it wants to follow that or do something else.

One thing I am not sure about, is that if what's just before / just after the caret isn't just text (for example, an image, a table, a table cell border...) what do we put in the target ranges? Whatever structure the browser would act on if it were to do the forward/backward deletion, somehow (how?) stick to information about textual content only? No information if the thing immediately before / after the care isn't text?

**Comment by johanneswilm** [comment]
> One thing I am not sure about, is that if what's just before / just after the caret isn't just text (for example, an image, a table, a table cell border...) what do we put in the target ranges? Whatever structure the browser would act on if it were to do the forward/backward deletion, somehow (how?) stick to information about textual content only? No information if the thing immediately before / after the care isn't text?

I am not sure I understand the issue. If there is an image just before it, so that the deletion would trigger for the image to be removed, I would image it would be a range that only covers the image and nothing else, right? Or what is it I don't get?

**Comment by johanneswilm** [comment]
From the description of static ranges, I would image that they can point to both text content and non-textual content. 

**Text content:**

```
<b>hello |there|</b>
```

StaticRange = start: {node: textnode, offset: 6}, end: {node: textnode, offset: 12}

**Non-text content:**

```
<b>hello|<img>|mellow</b>
```

StaticRange = start: {node: <b>, offset: 1}, end: {node: <b>, offset: 2}

**Comment by frivoal** [comment]
For an image, it is relatively unanbiguous. However, let's say the thing just before the caret is a table. Should the range contain the table? the last table cell? the last character in the last table cell? When moving away from exec command into JS driven things, this is precisely the kind of thing we want to leave up to JS.

If we include in the range whatever it is the browser would delete if it were the one doing the deletion and leave it at that, then JS has to go an analyze that, to see if it is a simple textual cases where it should follow the browser's advice by default, or if we're in a case where JS ought to make up its mind on its own. The risk is that naïve implementations may not think that there could be useful information about unicode characters in that range, and just always ignore it.

If instead we make it super easy to distinguish "this is just text deletion, and this range is one character worth of text", and "there's some markup in there, do your own thinking", we may increase the chance of naïve implementations getting text right.

**Comment by johanneswilm** [comment]
> For an image, it is relatively unanbiguous. However, let's say the thing just before the caret is a table. Should the range contain the table? the last table cell? the last character in the last table cell? When moving away from exec command into JS driven things, this is precisely the kind of thing we want to leave up to JS.

Well, execCommand isn't used today anyway, at least not for this. Right now one will listen for the keypresses that may cause deletion in either direction, then check what is in the direction that the deletion is to take place. In some cases, some editors then allow for the browser to do what it wants to do (for example because it determined there is just a character in front of it, and it trusts the browser to deal with that). If the caret is behind a table, it would usually delete the entire table. There may be some browser inconsistencies with this that I am unaware off, but those we will not fix right now.

Some browsers could indeed be so broken in every respect that one just chooses to completely ignore everything that the browser says about what it would do. But this would then likely apply both to table deletion as well as codepoint deletion.

> If instead we make it super easy to distinguish "this is just text deletion, and this range is one character worth of text", and "there's some markup in there, do your own thinking", we may increase the chance of naïve implementations getting text right.

If the range start-node and end node are the same and this node is a text node, we know it's character deletion. In all other cases it will be something else, right?

Additionally, we should probably add examples of this to the spec to make it clearer to everyone.

The function you are asking for may have more usecases though. Basically it would be about turning a string of unicode characters into an array of graphemes, right? This could be used if, for example, one wants to do grapheme deletion using backspace under all circumstances, even when the browser disagrees.

**Comment by frivoal** [comment]
> If the range start-node and end node are the same and this node is a text node, we know it's character deletion. In all other cases it will be something else, right?

Sounds right.

> Additionally, we should probably add examples of this to the spec to make it clearer to everyone.

Examples are always good.

> The function you are asking for may have more usecases though. Basically it would be about turning a string of unicode characters into an array of graphemes, right? This could be used if, for example, one wants to do grapheme deletion using backspace under all circumstances, even when the browser disagrees.

Yes, probably. At the same time, figuring out whether you're supposed to delete a single character, or the whole grapheme cluster is language dependent (and seems to be dependent of what you want to do with it, as it was earlier mentioned that you may not want to do the same when deleting forward and backward), it looks a bit tricky.

My goal here isn't so much to expose a general purpose text/unicode API allowing you to do all manners of smart things, but to help naïvely programmed editors to deal with international text simply without screwing everything up.

**Comment by johanneswilm** [comment]
> Yes, probably. At the same time, figuring out whether you're supposed to delete a single character, or the whole grapheme cluster is language dependent (and seems to be dependent of what you want to do with it, as it was earlier mentioned that you may not want to do the same when deleting forward and backward), it looks a bit tricky.

Yes, but as you mentioned, there may be variations in how to handle it from JS editor to JS editor. And from the CK editor discussion linked above, it seems like there are JS libraries to figure out about graphemes and code points. I guess one can guess which script is in use by looking at what unicode characters have been used.

> My goal here isn't so much to expose a general purpose text/unicode API allowing you to do all manners of smart things, but to help naïvely programmed editors to deal with international text simply without screwing everything up.

What are you proposing concretely?

I think the naively programmed editor will get most out of examples on this. As an editor developer, one currently has to spend a fair amount of time on creating a working minimal editor anyway (no less than 1-3 years if you have written another one before, else 3-8 years). And once you get the concept that in some languages graphemes consist of more than one character, you will also be able to write the 1 line check to see if we are just deleting text and if so, how many unicode characters using the targetRange. This should already make it a lot easier to handle this correctly than what is currently the case.

Also, we can add those examples to the description text for the inputtype, but right now I cannot think of how to add that without making it even more convoluted. Any suggestions on how to change:

> If the user intends to delete the content directly after
>                     the caret position and this intention is not covered by another
>                     inputType or the user itends to delete a non-collapsed selection
>                     with the selection collapsing to its end after the deletion,
>                     using a keyboard, speech, or similar method, the inputType
>                     MUST be

**Comment by frivoal** [comment]
> What are you proposing concretely?

That we don't generalize this to the need for an API to slice a string in varous codepoint / character compositions / graphemes.

Exposing what the "character" to be deleted through the `getTargetRanges()` seems basically the right thing, and all it needs is probably some extra prose to make sure that browsers know what they're supposed expose in these ranges, and some notes and example to guide authors on how to use it.

**Comment by johanneswilm** [comment]
Ok, it seems like we all agree then. I will wait another day and if we have no further information about this telling us that this is a bad idea, I will update the spec draft and close this issue. For similar issues, that are not exactly this, let's try to open other tickets.

**Comment by garykac** [comment]
That approach doesn't work well for ligatures:

Consider the 'fl' ligature ﬂ \xfb02

forward delete before the ligature should change the 'ﬂ' to an 'l'.
backward delete after the ligature should change the 'ﬂ' to an 'f'.

**Comment by johanneswilm** [comment]
What about moving the caret in a text with ligatures? Will it be able to go between the letters?

**Comment by johanneswilm** [comment]
Testig in contenteditable Chrome, it seems to treat the ligature 'fl' as a single character - so you can only move the caret around it and delete the entire thing. For Latin languages, I think this seems fine as standard browser behavior Advanced JavaScript libraries can come up with more advanced behavior.

**Comment by johanneswilm** [comment]
Testing in contenteditable in Chrome and Firefox, it seems to treat the ligature 'fl' as a single character - so you can only move the caret around it and delete the entire thing. For Latin languages, I think this seems fine as standard browser behavior. Advanced JavaScript libraries can come up with more advanced behavior.

In general, as I understand it, one is expected to have use the characters individually "fl" in the HTML markup, and it is then up to the renderer to display them as a ligature under certain conditions. For editors where the user gets to add ligatures, it would seem to make sense to let the user delte the entire thing as well by default.

Would any of you have examples of non-Latin languages where this would not be ok?

**Comment by johanneswilm** [comment]
Another option would be to enable the data attribute of the beforeinput event for such cases. So it could carry information about what character(s) to add in replacement of what is in the first targetRange.

But again, if there is no browser that currently handles this type of editing of text with ligatures in a special way, and additionally usage of ligatures in source text creates issues for moving the caret, this may not be all that important right now. What do you think @garykac ?

**Comment by johanneswilm** [comment]
@garykac: Could you open a new issue for the case of ligatures, given that this is an issue that is somewhat apart?
