### ISSUE TITLE
July 29th F2F Agenda Item - Dragging and dropping

### ISSUE THREAD

**Issue by gked** [w3c/editing#134]
What should the order of the events be and in what spec should this be placed?

**Comment by gked** [comment]
Resolution: In what order do dragend, input and drop events are fired and when is dom updated during those events in Edge. Then we can come to real resolution.

**Comment by garykac** [comment]
Current order for Cr, FF, Safari is:
- drop
- _(beforeinput should go here)_
- _update DOM_
- input
- dragend

Need to verify with Edge and confirm.

**Comment by garykac** [comment]
Spec also says something about updating the DOM on dragend if dragging selected text. Need to investigate and see what the browsers currently do. dragend may need to generate beforeinput/input events as well.

**Comment by gked** [comment]
Edge has bugs in this area.  Event sequence it fires is different from the rest:
- drop
- dragend 
- partial DOM update ( img element is being inserted after foo but not being removed before foo)
- dragend
- input 
  -DOM update

We'll fix the issue on our side as the behavior of the rest of the browsers makes sense.

To Gary's second comment, Edge does update the DOM after dragend is being fired but for images. This is probably why Edge tries to update the DOM once dragend is fired.

**Comment by johanneswilm** [comment]
This issue was moved to w3c/input-events#24
