### ISSUE TITLE
July 29th F2F Agenda Item - Clipboard events

### ISSUE THREAD

**Issue by gked** [w3c/editing#135]
Should paste and cut have beforeInput events? If so, should these be cancelable? Only in cE=events or also in cE=true?
Should copy also have a beforeInput event? What if there is no editing host involved?

**Comment by gked** [comment]
Resolution:
Should paste and cut have beforeInput events? Yes.
Should copy also have a beforeInput event? No
If so, should these be cancelable? Yes.
Only in cE=events or also in cE=true? It will apply to CE=true and CE=plaintext-only.
What if there is no editing host involved? No, since we are tying beforeInput event to Input event, and input events are only firing in editable regions.

**Comment by garykac** [comment]
Decision: Keep cut/copy/paste around
- They already ship, so there is code that depends on them
- Beforeinput doesn't handle the 'copy' case, and having 'copy' without 'cut' and 'paste' feels odd 

Event order:
- beforeinput
- cut (or paste)
- input

No beforeinput/input for copy events

What about Cancelable? (for contentEditable != false)
- canceling beforeinput (type=cut/paste):
  - prevents the cut/paste event
  - prevents dom update
  - prevents clipboard update
- canceling cut/paste:
  - prevents dom update
  - prevents clipboard update

Investigate where spec says paste events are not cancelable: Editing Spec 6.2 bullet point 6
