### ISSUE TITLE
July 29th F2F Agenda Item - History handling (undo/redo)

### ISSUE THREAD

**Issue by gked** [w3c/editing#136]
What should the relationship between browser-controlled editing history and beforeInput event be? Should redo/undo have beforeInput events?
If JS handles beforeInput events, should the browser try to figure out what changes were made? Is that technically possible?

**Comment by gked** [comment]
Resolution:
Should redo/undo have beforeInput events? Yes.
What should the relationship between browser-controlled editing history and beforeInput event be?  Browser Undo stack stays un-affected and dom is not being affected.
If JS handles beforeInput events, should the browser try to figure out what changes were made? Is that technically possible? left for future discussion, not blocking beforeInput event spec.

**Comment by garykac** [comment]
event order:
- beforeinput type='undo'
- undo/redo event
- _Dom update_
- input

If preventDefault:
- No DOM update
- no input event fired
- The browser undo/redo stack is not changed

**Comment by johanneswilm** [comment]
This issue was moved to w3c/input-events#15
