### ISSUE TITLE
Support for custom Responsive Input events

### ISSUE THREAD

**Issue by joanmarie** [w3c/editing#14]
In addition to "traditional" events (e.g. moving the caret, changing the selection, moving to the next focusable item), web applications have custom events for which intention events may be applicable. 

Example 1: In Twitter, j and k move to the next and previous tweet respectively.

Example 2: A <hypothetical> music service web app in which N plays the next song in the playlist and P plays the previous song in the playlist.

In both cases, the intent of the user is to perform a relatively common action. Thus perhaps the set of user intention event types should be expanded to include these sorts of actions. Alternatively, perhaps there should be support for custom intention event types.

**Comment by johanneswilm** [comment]
Ok, but we already have ways to listen for key clicks in Javascript and it is fairly easy to have set up one way of listening to a series of key combinations and then initiate various things, such as "Save", "go to next", "close", etc. . 

Maybe there are other good use cases for this that I cannot think off, but it seems like that should then be a spec of its own and not depend on whether or not there is a contenteditable=typing element on the page.

I will close this for now, but please reopen if this has been misunderstood.
