### ISSUE TITLE
Time at TPAC?

### ISSUE THREAD

**Issue by LJWatson** [w3c/editing#165]
Would you like time at [TPAC](https://www.w3.org/2017/11/TPAC/) to update the WG on progress and/or bring issues up for discussion?

Please let me know by Friday 16th June. If yes, please also let me know how much time you think you'll need.

**Comment by johanneswilm** [comment]
Hey, @chaals asked us about this about a month ago. I will email you now.

**Comment by LJWatson** [comment]
Thanks @johanneswilm. @Chaals has been focused elsewhere this week, so I'm picking up on TPAC scheduling. Will reply to your email.
