### ISSUE TITLE
Should a styled paragraph maintain its own style when inserting it in a list ? 

### ISSUE THREAD

**Issue by javifernandez** [w3c/editing#179]
Lets consider the following code:

```
<div id='test' contenteditable='true'>
    <div id='test0'>
      <span id='test0-1' style="font-style: italic; color: rgb(00, 255, 00)">This text should be green italic</span>
    </div>
    <div id='test1'>
        <ul style="font: 20px/1 monospace; color: blue;">
            <li>List item 1</li>
        </ul>
        <span id='test2' style="font-style: italic; color: rgb(00, 255, 00)">This text should be green italic</span>
    </div>
</div>
<script>
var d = document.getElementById('test');
d.focus();
var sel = document.getSelection();
var range = sel.getRangeAt(0);
d = document.getElementById('test2');
range.selectNode(d)
range.collapse();
document.execCommand('insertUnorderedList');
</script>
```

As far as I know, when applying the _insertOrderedList/insertUnorderedList_  command, the newly created list item has to be merged with its previous list element sibling. The question is, what's the expected behavior regarding the paragraph's style ? Should we keep it even implying we'll breaking the list element's style ? 

What would be the behavior if there was no previous list element sibling and the selected text will become the only list item if the newly created list ?  Should we keep the paragraph's style in that case ? 

Depending on the answers to the questions above, should we behave differently in those cases ? Why ? IS there any spec/doc describing how to proceed in the different cases where text paragraphs are transformed into list items via  the _insertOrderedList/insertUnorderedList_ command ?

**Comment by javifernandez** [comment]
As far as I could evaluate, this is the current behavior of some of the main browsers when loading the code above (and also the one without an existing list element):

<table>
<tr><td></td><td align="center">Create a new list</td><td align="center">Use an existent list</td></tr>
<tr><td><b>Chrome 70</b></td><td><img src="https://user-images.githubusercontent.com/2230241/45391152-3f2f2e00-b622-11e8-97ee-2459033e0ce9.png"></td><td><img src="https://user-images.githubusercontent.com/2230241/45391150-3f2f2e00-b622-11e8-9dd7-e99f39f6d420.png"></td></tr>
<tr><td><b>Firefox 62</b></td><td><img src="https://user-images.githubusercontent.com/2230241/45391153-3fc7c480-b622-11e8-8a3f-4a8aa2f1d8d6.png"></td><td><img src="https://user-images.githubusercontent.com/2230241/45391149-3f2f2e00-b622-11e8-81d3-3d1f611fe27e.png"></td></tr>
<tr><td><b>Edge 17</b></td><td><img src="https://user-images.githubusercontent.com/2230241/45391154-3fc7c480-b622-11e8-9559-2bad7094c595.png"></td><td><img src="https://user-images.githubusercontent.com/2230241/45391155-3fc7c480-b622-11e8-8994-2d118f353d4a.png"></td></tr>
<tr><td><b>Safari Tech Preview</b></td><td><img src="https://user-images.githubusercontent.com/2230241/45391167-481fff80-b622-11e8-9782-6e44248d73c2.png"></td><td><img src="https://user-images.githubusercontent.com/2230241/45391168-481fff80-b622-11e8-809e-7262bd2dffd4.png"></td></tr>
</table>

**Comment by johanneswilm** [comment]
AFAIK, there is no spec for this and this seems like extremely messy code to be dealing with. This clearly falls into the domain of JavaScript code cleaning it up which will be highly depending on what kind of editor we are working with, at least the web works is in 2018. Also, we are not actively working on execCommand.

That being said, as long as you are making browsers work more similarly,  that will in general make it easier to work with for JavaScript code.

**Comment by javifernandez** [comment]
Ok, thanks for the info. I'm working now on changing Chrome's behavior regarding the text's style. If it's eventually accepted, at least it'll improve interoperability.  The issues about the order of the elements after the execCommand will remain, though.

**Comment by johanneswilm** [comment]
@javifernandez Ok, you are making Chrome more similar to which other browser then?

**Comment by javifernandez** [comment]
Chrome will match Firefox exactly for this use case.

**Comment by rniwa** [comment]
FWIW, we're not going to change WebKit's behavior here. The current behavior is required to match the platform behavior we have.

**Comment by javifernandez** [comment]
I fixed Chrome's behavior to match Firefox in https://crrev.com/c/1216282 so I think we can close this issue now.
