### ISSUE TITLE
How should custom controls declare their Responsive Input mapping?

### ISSUE THREAD

**Issue by BenjamP** [w3c/editing#18]
At the moment the spec has a declareIntention() function, allowing sites to create input type="button" onclick="declareIntention('bold')" so they can create toolbars and such. This has a side effect of allowing Responsive Input to be declared outside of User Actions though, which seems like it breaks the model. Perhaps a better way to would be input type="button" intention="bold". Or we could use the menuitem element.

**Comment by KenjiBaheux** [comment]
When/Why would the ability to declare an intent outside of user actions be a bad thing?

**Comment by BenjamP** [comment]
In my opinion, the goal of Responsive Input is to capture what a user Intends by performing an Action. I want to keep this from being perceived as a way to call a function. For example, a site could properly use Responsive Input like this:

Keyboard Event Control+B = Bold Event
Saying "Bold" = Bold Event
Clicking bold button = Bold Event

Then the Bold Responsive Input Event calls a custom bold function

But then the site decides to bold text for another reason, say a concurrent user bolded text, or the site was bolding text as part of custom undo, or text was bolded automatically from sites context highlighting behavior. In this case, the site might be tempted to declare a bold event. But that breaks the model here. Instead, they should just call their Bold function, like they do inside the Bold event handler.

Does that make sense?

**Comment by rniwa** [comment]
I think the command element we had in HTML5 spec. draft at some point in the past was a nice model.  It declared an actionable item in the page in such a way that it could be associated with a specific key combinations but also allowed UAs to expose those actions in alternative fashions; e.g. via menu.

**Comment by BenjamP** [comment]
Actually we need to be able to declare intentions from inside keyboard events too so we can change keyboard bindings. I think the best way to to this is to include a declareIntention on mouseEvent, keyboardEvent, clipboardEvent, dragEveng, and anywhere else that a user might be intending to insert, delete, type, etc. That way only these 'user-initiated' actions result in Responsive Input Events.

**Comment by johanneswilm** [comment]
We could also just drop the formatting events entirely, at least for contentEditable=Typing. That would remove the need to change bindings and simplify everything a fair bit. Otherwise this seems as somewhat of a reinvention of execCommand("bold") which never really worked for the end user anyway. If there is a button to bolden things, the clock event can tell the user Javascript about that and set it up so that that triggers the same function that already is bound to CTRL+B.

**Comment by johanneswilm** [comment]
Given the limited resources we have, and given that this can already be achieved in user space by means of listening to key strokes and calling functions that then make things bold, save files, etc., I will close this for now.
