### ISSUE TITLE
2019 TPAC Agenda for Editing TF

### ISSUE THREAD

**Issue by gked** [w3c/editing#198]
Hi All, 
Here are few things that we wanted to talk about during the TPAC. Feel free to add/comment.

- [EditContext API](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/EditContext/explainer.md) (2 hours)
- [Highlight API](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/highlight/explainer.md) (2 hours)
- [Remaining gaps in async clipboard API](https://bugs.chromium.org/p/chromium/issues/detail?id=931839) (2 hours) - We are thinking of picking up the work where Chrome's team left of. Specifically, building support for html mime type and implementing clipboardChange event.
[Raw Clipboard Access](https://tinyurl.com/raw-clipboard-access-design) - (1hour) Discuss the API with other browser vendors and interested developers.
[contenteditable-disabled](http://w3c.github.io/editing/contentEditableDisabled.html) (1 hour)
- [PenEvents](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/PenEvents/explainer.md) (30 minutes)
- Spellcheck APIs (30minutes)- inspired by https://github.com/w3c/editing/issues/166.
wanted to gauge the interest from editing frameworks and other js developers.
wanted to walk though use cases and hopefully, agree on the shape of the API if time allows.
- [SIP policy](https://github.com/whatwg/html/issues/4876) (30 mins)- we've received a request from Excel online and Google Docs asking for a way to control SIP. Excel's use case is to prevent SIP from showing up when editable element is focused. Google Docs has mentioned to have an explicit API for the virtual keyboard on touchscreen devices, particularly for showing/hiding the keyboard and querying its current state.. This is needed in cases where users would want to maintain editability of an element without invoking the SIP. We wanted to gauge interest in the community for this API
- SIP coordinates (30 mins) - today, on Windows, Input service communicates the coordinates of the SIP once it shows up on the screen. Office online has expressed the desire to for these events to be exposed to JS. We wanted to gauge interest in the community for this API. Somewhat overlaps with [this](https://github.com/w3c/editing/issues/183)?
- Static Ranges [applicability](https://github.com/whatwg/dom/issues/590) (30 mins)
- Range in native elements (1 hour)
- Range events (1 hour)

**Comment by marcoscaceres** [comment]
Thanks @gked! Would you mind adding links to the newer proposals above?

**Comment by gked** [comment]
> Thanks @gked! Would you mind adding links to the newer proposals above?

yep, working on it. Will update the post soon

**Comment by rniwa** [comment]
On which date are we having this F2F?

**Comment by dway123** [comment]
I'd also like to talk about [Raw Clipboard Access](https://docs.google.com/document/d/1XDOtTv8DtwTi4GaszwRFIJCOuzAEA4g9Tk0HrasQAdE/edit#), and would like to +1 the Async Clipboard API

**Comment by dway123** [comment]
Chrome is planning to implement [Raw Clipboard Access](https://tinyurl.com/raw-clipboard-access-design), and we'd like to discuss the API with other browser vendors and interested developers. Also, +1 to Async Clipboard API gaps.

**Comment by androb** [comment]
We should be able to get someone from the TinyMCE team to attend. When (and where) is this F2F planned?

**Comment by LJWatson** [comment]
We have a room for up to 15 people on Friday. I'm working to get it 
added to the registration form separately, but in the meantime please 
register for WebApps since the TF is part of that WG anyway.

**Comment by johanneswilm** [comment]
We should also speak about  [contenteditable-disabled](http://w3c.github.io/editing/contentEditableDisabled.html).

**Comment by gked** [comment]
Added Raw Clipboard Data and contenteditable-disabled to the list of agenda items.

I've also added times needed to be spent on each issue but they are most definitely estimates. 
I am wondering whether we should have a call or two before TPAC so we can identify most critical questions and it would also help us refine time estimates? Let me know if anyone is interested.

Looking at the estimates, it could potentially take us more than one day to go over all of the issues. @LJWatson  and @marcoscaceres  do you think there is an opportunity to get a day and an half or two days for editing related questions?

**Comment by johanneswilm** [comment]
Contenteditable-disabled of about 1 hour sounds right. I don't have much to say except that I have tried to get those things we discussed and decided on last year into writing and then I haven't heard back from anyone since then. This continues to be an important issue for JavaScript editors, so it would be good to hear what other changes we need to do on it (if any) so that it is something browser makers would consider implementing (applies mainly to Safari, but probably also to Chrome/Android) or whether we need to redo it entirely.

I'm up for a call if there's interest in that.

**Comment by Reinmar** [comment]
Will it be possible to join remotely, at least to listen? Unfortunately, I won't be able to attend in person this time.

**Comment by LJWatson** [comment]
I'm checking availability of remote dial facilities, and will let you know.

The Editing TF meeting should now be an option on the TPAC registration 
form. It would be helpful if you could update your registrations to 
acknowledge you'll be attending. Thanks.

**Comment by LJWatson** [comment]
There will be remote dial capability, and I'll make sure that a WebEx has been created for the meeting.

**Comment by dway123** [comment]
I would be interested in identifying critical questions/refining time estimates. If we do a call, I'm interested in joining.

If we can't book more time for the Editing, could we also consider doing topics in parallel? Or reducing time estimates?

**Comment by LJWatson** [comment]
@johanneswilm

Have we let the CSS WG know about the proposal to discuss the Highlight API? If not, we need to get an invitation over to the CSS WG chairs ASAP. To do this, it'd help to know what time of the day you plan to have that particular discussion?

Thanks.

**Comment by dway123** [comment]
> On which date are we having this F2F?

This will be on Friday, 9/20, according to https://www.w3.org/2019/09/TPAC/schedule.html

**Comment by gked** [comment]
@LJWatson, yep, we are working on it. @sanketj as FYI. We were looking to do this on Monday if possible.

**Comment by johanneswilm** [comment]
@ljwatson I was assuming that we will only look at the Highlight API to determine whether it is something that would be useful to us and that we then transfer it to the CSS WG. Is that not so @gked ?

**Comment by LJWatson** [comment]
> I was assuming that we will only look at the Highlight API to determine whether it is something that would be useful to us and that we then transfer it to the CSS WG.>

My understanding is that the [Highlight API](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/highlight/explainer.md) is a proposed extension to the [CSS Pseudo Elements module](https://drafts.csswg.org/css-pseudo-4/#highlight-pseudos), so it's already on the CSS WG radar?

It seems there is a definite overlap of interest in this proposal though, so a discussion here makes sense in any case.

Courtesy ping to CSS chairs @atanassov and @astearns, plus @fantasai and @frivoal.

**Comment by frivoal** [comment]
> This will be on Friday, 9/20
What time is that discussion scheduled? I'd like to attend, but I probably won't join the whole day.

> My understanding is that the Highlight API is a proposed extension to the CSS Pseudo Elements module

Indeed.

> so it's already on the CSS WG radar?

The concept has been discussed with and received support from a number of CSSWG people. I think next steps are to move from an Explainer, and start writing an actual spec, and publish it there as an FPWD. I'm happy to contribute to making that happen. I do think a discussion in the Editing TF makes sense, as you are likely to have a number of important use cases, and we don't want to overlook them.

**Comment by gked** [comment]
@frivoal do you mean that Highlight API was discussed at one of CSSWG calls, emails or face-to-face? If so, this is great. Are there any minutes that you can link us to so we can take a look at feedback? 

Also do you think it would be beneficial for us to get a spot on CSSWG agenda at TPAC to walk people through the explainer and discuss potential direction for specific issues?

tagging others as well @atanassov, @astearns, @fantasai and @tabatkins.

**Comment by gked** [comment]
@johanneswilm @dway123  @BoCupp @Reinmar @androb  and anyone else who may be interested in having an one hour or so prep for Friday

I've been out for a month and didn't get a chance to setup few calls for us before TPAC. 

Nevertheless, I've reached to webapps group asking for a webex space and a phone number to setup a call for this Thursday but I feel like it is a bit of a too short of a notice for everyone.

How do people feel about us spending some time discussing the objectives and to set expectations for each agenda item before Friday? I will look into the possibility to have phone lines for that occasion as well. This should help us to get time estimates right and move the stuff that would not fit on Friday into Wednesday or Thursday as adhoc sessions.

If that works for you, I created agenda file so people can edit on their own- https://github.com/w3c/editing/blob/gh-pages/TPAC/2019/Agenda.md

**Comment by frivoal** [comment]
> @frivoal do you mean that Highlight API was discussed at one of CSSWG calls, emails or face-to-face? 

Not quite. I don't believe we had it on the agenda during a minuted session, but I remember talking about it during breaks with multiple people, and everyone I talked to was supportive, at least at the abstract level.

I do think it would be a good idea to bring this to the CSSWG during, for somewhat more official feedback. My expectation is that the CSSWG will agree to start work on this topic, action some people (you, maybe together with me) to write an Editor's Draft, with the intent of publishing a FPWD before too long and to start tackling issues individually.

**Comment by whsieh** [comment]
Hi folks! If time allows, I’d like to discuss a proposal for the UndoManager API (explainer: https://whsieh.github.io/UndoManager and spec: https://rniwa.github.io/undo-api).

**Comment by johanneswilm** [comment]
@whsieh I think we should find time for that. Where should we put questions/comments for that proposal? I have posted one issue here: https://github.com/rniwa/undomanager/issues

**Comment by rniwa** [comment]
Please don’t file issues in my personal repos. If you find any issues with it, please file an issue in this repo instead.

**Comment by johanneswilm** [comment]
@rniwa Will you also move the spec draft to this repository then? if we have the discussion here but the drafts somewhere else, that seems slightly confusing.

**Comment by whsieh** [comment]
> @whsieh I think we should find time for that.

Ah, so I proposed this as a plenary session idea here: https://www.w3.org/wiki/TPAC/2019/SessionIdeas#UndoManager_API. An hour on Wednesday (including a brief presentation) might be sufficient, though we could consider extending discussions to Friday if necessary.

**Comment by rniwa** [comment]
> @rniwa Will you also move the spec draft to this repository then? if we have the discussion here but the drafts somewhere else, that seems slightly confusing.

That will depend on where this proposal / spec would ultimately live. I've taken the repository so that nobody will find it to avoid the confusion. The repository isn't meant for any public consumption.

**Comment by johanneswilm** [comment]
@rniwa Could we get a readme in that repository that links to where the discussion is to take place? @gked Similarly for this year's Microsoft proposals, it wasn'tentirely clear to me where the discussion on those is to take place. Could we have some common standard of one finds the place to discuss?

**Comment by rniwa** [comment]
> @rniwa Could we get a readme in that repository that links to where the discussion is to take place?

I took it private so nobody will find it.

**Comment by johanneswilm** [comment]
@rniwa: So we should not discuss it at TPAC next week then?

**Comment by rniwa** [comment]
> @rniwa: So we should not discuss it at TPAC next week then?

We should discuss it at TPAC. There is **no repository** is what I'm trying to say. What we're presenting is https://whsieh.github.io/UndoManager and https://rniwa.github.io/undo-api and no more or no less.

**Comment by sanketj** [comment]
> > @frivoal do you mean that Highlight API was discussed at one of CSSWG calls, emails or face-to-face?
> 
> Not quite. I don't believe we had it on the agenda during a minuted session, but I remember talking about it during breaks with multiple people, and everyone I talked to was supportive, at least at the abstract level.
> 
> I do think it would be a good idea to bring this to the CSSWG during, for somewhat more official feedback. My expectation is that the CSSWG will agree to start work on this topic, action some people (you, maybe together with me) to write an Editor's Draft, with the intent of publishing a FPWD before too long and to start tackling issues individually.

@frivoal , @LJWatson, @gked : I have filed an issue (https://github.com/w3c/csswg-drafts/issues/4307) to include the highlight API in the CSS WG agenda for TPAC. Feel free to take a look. Thanks!

**Comment by johanneswilm** [comment]
@rniwa @whsieh Ok, I've added a comment here: https://github.com/w3c/editing/issues/209

**Comment by dway123** [comment]
Sorry for the super late notice, but could we also discuss a potential [clipboard mark of the web](https://github.com/dway123/clip-motw/blob/master/explainer.md)? 30 min should be good.

**Comment by gked** [comment]
Closing as TPAC is over.
