### ISSUE TITLE
How should execCommand map to inputType?

### ISSUE THREAD

**Issue by saschanaz** [w3c/editing#201]
A simple behavior test in https://codepen.io/SaschaNaz/pen/WNepGPa says that both Firefox and Chrome dispatches `input` with `inputType: "formatBold"` while Safari dispatches with `inputType: ""` for the same `execCommand("bold")`. As there is no standard mapping between `execCommand` commands and `inputType` of `InputEvent`, what's the expected behavior here?

**Comment by rniwa** [comment]
That just sounds like a bug in Safari / WebKit. @whsieh

**Comment by whsieh** [comment]
Yeah, this sounds like a bug. Filed: <https://bugs.webkit.org/show_bug.cgi?id=201128>.

**Comment by johanneswilm** [comment]
It seems like this relates to https://github.com/w3c/editing/issues/194 and this is also something that should go into the execCommand spec.
