### ISSUE TITLE
behavior of text nodes inside cE=typing

### ISSUE THREAD

**Issue by teleclimber** [w3c/editing#22]
I recently filed a bug in the Chromium project:
https://code.google.com/p/chromium/issues/detail?id=436107

The problem I had was that Chrome was removing a text node. This causes problem in my code because I keep references to text nodes. Having a node vanish from the document is frustrating thing to have to deal with when you are writing an editor.

I think cE=typing should specify a few behaviors for text nodes contained within it. The behaviors would be in line with the "no magic" ideas of cE=typing.

Some examples:
- don't unilaterally remove, modify, join, split text nodes
- allow empty text nodes

The bug on Chromium is marked as won't fix, and frankly I can't blame them. However, we should collect all the magical behaviors related to text nodes on all UAs that make editing very hard and spec the proper non-magical behavior in cE=typing.

**Comment by johanneswilm** [comment]
I think this should take care of it https://github.com/w3c/editing-explainer/commit/2ea888816a9ac50c143377efab883bb3cf7eaa9c . It defines that no text nodes are changed by the movement of the caret. And https://github.com/w3c/editing-explainer/commit/84239e25bc94f89ff047d5c0aeb89f33eb7d7366 which adds basic info on how text is inserted and that it will not cause merging or removal of text nodes.

I will close this issue, as I think it has been addressed. Please reopen if you think it needs further specification.
