### ISSUE TITLE
CFC: Editing TF co-facilitators and work statement

### ISSUE THREAD

**Issue by LJWatson** [w3c/editing#221]
This is a Call For Consensus (CFC) to invite Johannes Wilm (Invited Expert) and Grisha Lyukshin (Microsoft) to become co-facilitators of the WebApps Editing Task Force (TF), and to adopt the draft [Editing TF work statement](https://github.com/w3c/editing/blob/gh-pages/CHARTER.md).

The Editing TF has been in existence since the time of the original WebApps WG, it continued to operate under the WebPlat WG, and is now part of the (recently reformed) WebApps WG once again. The work statement reflects the current scope and deliverables of the Editing TF, and the introduction of two co-facilitators is intended to help drive the work forward.

If you support this proposal you don't have to respond to this CFC, though you're welcome to add a "thumbs up" reaction to this comment if you'd like to.

If you don't support this proposal, please post your reasons as clearly as possible in a new comment on this issue.

This CFC will stay open until the end of the day on Friday 15 November 2019. If you want to respond, please do it before then.

**Comment by travisleithead** [comment]
I strongly support this CfC

**Comment by yosinch** [comment]
Thanks Grisha to accept to the role!
Strongly support this CfC.
👍

**Comment by LJWatson** [comment]
This CFC received only messages of support, and no objections.

Congratulations Johannes and Grisha!
