### ISSUE TITLE
execCommand archive link is broken

### ISSUE THREAD

**Issue by jdm** [w3c/editing#247]
https://w3c.github.io/editing/#archive-3 includes a link to execCommand that doesn't work.

**Comment by jdm** [comment]
Should execCommand.html be moved into Archived from ActiveDocuments? Links on MDN to the spec are also broken because of this.

**Comment by johanneswilm** [comment]
@gked @marcoscaceres I believe you people were moving things around lately. What do you think?

**Comment by saschanaz** [comment]
#264 fixed this 👍
