### ISSUE TITLE
fontSize / insertImage is not in the in input types list

### ISSUE THREAD

**Issue by gked** [w3c/editing#249]
fontSize / insertImage is missing from [input events](https://www.w3.org/TR/input-events-1/). It seems that it should be listed to create a more complete set. 

What was the rationale behind keeping it out?

**Comment by johanneswilm** [comment]
I believe the rationale behind not including these was that at the time we were not aware of browser native controls to do these actions.

**Comment by gked** [comment]
per discussion on TF Editing call on May8th, 2020 we will postpone adding commands we have no known use cases for. Also, please make sure current PR doesn't include them.
