### ISSUE TITLE
Rename Archive directory as Inactive

### ISSUE THREAD

**Issue by saschanaz** [w3c/editing#253]
Per https://github.com/w3c/editing/pull/245#issuecomment-627148935, specs in `Archive` directory can still be modified if needed. It's a bit misleading as archives often are not intended to change, how about renaming it to `Inactive`?

Also, why uppercase BTW?

**Comment by gked** [comment]
@saschanaz I agree with your rationale. +1 on renaming.

**Comment by saschanaz** [comment]
@gked Do you prefer `Active/Inactive` or `ActiveDocuments/InactiveDocuments`?

Or even `docs/[in]active`? 🤔 Personally I prefer just `docs` for active documents and `docs/inactive` for inactive ones.

**Comment by gked** [comment]
docs/[in]active looks even better. I imagine, we would need to add graduated in docs/ as well.
