### ISSUE TITLE
Create an issue on HTML spec to export "unordered set of unique space-separated tokens" into xref

### ISSUE THREAD

**Issue by gked** [w3c/editing#258]
New version of contenteditabledisabled draft references a term not supported by xref: "unordered set of unique space-separated tokens" into xref.

**Comment by marcoscaceres** [comment]
assigning to myself to follow up with HTML folks...

**Comment by marcoscaceres** [comment]
Sent PR https://github.com/whatwg/html/pull/5622

**Comment by marcoscaceres** [comment]
Merged - should work now :)
