### ISSUE TITLE
execCommand.html is a 404

### ISSUE THREAD

**Issue by annevk** [w3c/editing#261]
https://w3c.github.io/editing/execCommand.html doesn't load. The HTML standard has at least one link there and probably more, that page should continue to exist or redirect somewhere useful.

**Comment by annevk** [comment]
It seems this happened in #233. Please revert that.

**Comment by Tanja-4732** [comment]
The link specified by @annevk seems to work now.

Should this issue be closed?

**Comment by Tanja-4732** [comment]
![image](https://user-images.githubusercontent.com/18219148/85231968-fa8e1480-b3fb-11ea-9ab6-eb0ee6d7b03e.png)

**Comment by annevk** [comment]
I think the plan was to also update the links in the HTML Standard or did I miss a PR?

**Comment by marcoscaceres** [comment]
Sent https://github.com/whatwg/html/pull/5671
