### ISSUE TITLE
EditContext: Change "focus" to "activate" to avoid confusion with the focus in the activeElement

### ISSUE THREAD

**Issue by BoCupp-Microsoft** [w3c/editing#269]
Moving [this EditContext issue](https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/99) into the editing repo.

From @snianu:
>EditContext's focus doesn't steal the focus away from DOM. This creates confusion so consider renaming it to something else (Activate?)

**Comment by BoCupp-Microsoft** [comment]
Note that we may revisit this concept since the latest thinking is that an EditContext can be associated with one or more DOM elements.  With that approach it may make sense to automatically activate and deactivate the EditContext as the corresponding elements are focused or blurred.  

Despite the above, I have created a pull request since at a minimum we won't want the `EditContext` APIs to remain named `focus` and `blur`.

**Comment by snianu** [comment]
@alexkeng FYI..

**Comment by alexkeng** [comment]
close this issue since we have chagned to automatically activate and deactivate the editContext as the assoicated elements are focused or blurred:
2794801: EditContext: bind editContext.focus with element.focus | https://chromium-review.googlesource.com/c/chromium/src/+/2794801
