### ISSUE TITLE
Add a way to query for the list of enabled commands in contenteditabledisabled spec

### ISSUE THREAD

**Issue by gked** [w3c/editing#272]

**Comment by johanneswilm** [comment]
@gked Look at the part about "supported" in the current document. What we want to get back in the PR on that spec is that functionality in some shape or form. https://github.com/w3c/editing/blob/gh-pages/docs/contentEditableDisabled/index.html#L38-L43

**Comment by johanneswilm** [comment]
As this was a request on changing a PR that was deleting a part of the existing text, we simply don't merge the part that was deleting the `DOMCommandTokenList` and its `supported` attribute.
