### ISSUE TITLE
Should parts of Input Events level 2 be moved to level 1?

### ISSUE THREAD

**Issue by johanneswilm** [w3c/editing#275]
When we created level 1 and 2 of Input Events it was because the Chromium team found it impossible to make some beforeinput events cancelable in what was then the unified Input Events spec and which is now known as level 2.  Particularly any inputType that added or removed content was to not be cancelable in Chromium. So we made a level 1 that did not specify that they were cancelable and a level 2 that specified that almost all beforeinput events were cancelable.

However, now it seems like Chromium currently actually does allow a lot (all?) of those that are undefined in level 1 to be cancelable. The question is then - if both Chromium and Webkit have implemented this part of level 2 and noone has implemented just level 1, should we move this from level 2 to level 1 so that the delta between the two is smaller? 

See https://jsfiddle.net/yv1sg2td/7/
See also https://github.com/w3c/input-events/issues/115

**Comment by gked** [comment]
@alexkeng and @snianu do you know if the change was intentional? If so, +1 to @johanneswilm proposal to update the spec.

**Comment by johanneswilm** [comment]
Yes, even if it was not intentional I am wondering if this will be reverted now that it has shipped like this in Chromium already? The current behavior is the same as Webkit.

**Comment by snianu** [comment]
Adding @NavidZ @bokand as I'm not sure who implemented the input events in Chromium and if these changes were intentional.

**Comment by NavidZ** [comment]
FYI @mustaqahmed as for the current owner of the code base.

**Comment by johanneswilm** [comment]
ping @mustaqahmed

**Comment by gked** [comment]
Ok, I've done some digging.
This commit introduced the change: https://chromium-review.googlesource.com/c/chromium/src/+/1585167
And this is the bug that requested it: https://bugs.chromium.org/p/chromium/issues/detail?id=892360&q=892360&can=2

In the bug, there is an ask to make Chrome comply with Level 2 spec.

I would agree with @johanneswilm 's analysis and don't think this was accidental nor that it will be reverted.

I support making the change to the spec.

**Comment by mustaqahmed** [comment]
I also support the change.  Thanks @gked for covering my absence.

**Comment by gked** [comment]
@johanneswilm proposing to close this issue. Thoughts?

**Comment by johanneswilm** [comment]
I agree. Let's close it.
