### ISSUE TITLE
Updates to execCommand spec

### ISSUE THREAD

**Issue by njdjacobs** [w3c/editing#288]
[Section 8, "Inline formatting commands"](https://w3c.github.io/editing/docs/execCommand/#inline-formatting-commands) includes superscript but not subscript in the list of contents (it's in the document but not in the list of contents).

**Comment by johanneswilm** [comment]
Hey @njdjacobs Absolutely. The subscript command seems to be there. But a missing `</section><section>` makes it not appear in the overview.
