### ISSUE TITLE
[charter] consider a more specific name for the Group

### ISSUE THREAD

**Issue by swickr** [w3c/editing#296]
"Editing" is very generic term and the scope of this charter is specific to browser (or maybe web client) - based editing.

I suggest "In-Browser Editing Working Group" would better state the intended scope and therefore be of more utility to people who are browsing lists of Groups they might care to join.

(Also, the acronym IBE WG is perhaps more interesting that EWG)

**Comment by siusin** [comment]
In-Browser Editing Working Group, Web Editing Working Group, or Fully Featured Browser Editing WG? Any other suggestions? What would the group prefer?  @johanneswilm @gked

**Comment by johanneswilm** [comment]
My preference order from highest to lowest would be: Richtext Editing Working Group, Editing Working Group, Web Editing Working Group, In-Browser Editing Working Group, Fully Featured Browser Editing Working Group. 

But I don't have a strong opinion about this. If we want more input on this issue, we could send out an email to the public editing tf email list.

**Comment by gked** [comment]
Doesn't the fact that it's a W3C group implies it is in fact web editing?
In any case, I don't have a strong opinions either. I like Web Editing Working Group. The reason I held back with Richtext Editing is that we also work with plain text. If folks don't mind, let's go with Web Editing Working Group.

**Comment by johanneswilm** [comment]
Ok, let's go with **Web Editing Working Group** then.
