### ISSUE TITLE
[charter] "on the web" implies protocol work; does this charter expect any?

### ISSUE THREAD

**Issue by swickr** [w3c/editing#297]
In section "1.2 In Scope" one finds the statement

> ... all aspects of text editing on the web ...

"On the web" connotes network activity to many of us.  Is there any work planned, or likely to be planned, on network protocols?  If not then perhaps stating the scope as

> ... all aspects of text editing in web browsers ...

would be more clear.

**Comment by johanneswilm** [comment]
No work on network activity is planned as far as I am aware. So yes, I agree that we should change this.
