### ISSUE TITLE
Should undo/redo be beforeInput events?

### ISSUE THREAD

**Issue by BenjamP** [w3c/editing#30]
How do we determine when we need a new event? Or is everything just going to use beforeInput? This also applies to custom events if we support them, like 'checkout' event or 'save' event.
-From MS Office Team

**Comment by johanneswilm** [comment]
Is there any advantage to have custom events handled by the browser rather than directly through the client?

**Comment by johanneswilm** [comment]
As for custom events: We already have ways to listen for key clicks in Javascript and it is fairly easy to have set up one way of listening to a series of key combinations and then initiate various things, such as "Save", "go to next", "close", etc. . 

Maybe there are other good use cases for this that I cannot think off, but it seems like that should then be a spec of its own and not depend on whether or not there is a contenteditable=typing element on the page.

I will close this for now, but please reopen if this has been misunderstood.
