### ISSUE TITLE
VirtualKeyboard spec feedback

### ISSUE THREAD

**Issue by yoavweiss** [w3c/editing#314]
Looking at https://w3c.github.io/editing/docs/virtualkeyboard/, there are a few points that can be made clearer:
* In [section 3](https://w3c.github.io/editing/docs/virtualkeyboard/#the-virtualkeyboard-interface), "If the browsing context's active window" is inaccurate. It'd be better IMO to replace it with "[this](https://heycam.github.io/webidl/#this)'s [relevant global](https://html.spec.whatwg.org/#concept-relevant-global)" while asserting that it's indeed a Window (which it should be, as the method is only exposed on a Window).
* I'm assuming that step 5 in both `show()` and `hide()` should be run in parallel, and the event doesn't fire synchronously. You should make that explicit. Depending if step 4 takes time, you may also want to run it in parallel as well.
* `overlaysContent` is missing a setter that would impact processing of the virtual keyboard and its interaction with the content. As is, it's really unclear what it's supposed to be doing. (e.g. I'm assuming you didn't mean for it to impact viewport changes that are unrelated to virtual keyboards)
* `boundingRect` should have a clear getter that defines what the returned values are.

/cc @gked

**Comment by snianu** [comment]
@yoavweiss Addressed all your comments [here](https://github.com/w3c/editing/pull/317)

**Comment by snianu** [comment]
This issue has been addressed in the linked PR.
