### ISSUE TITLE
Adopt Virtual Keyboard Policy / Control?

### ISSUE THREAD

**Issue by travisleithead** [w3c/editing#322]
Right now, we point over to MS Edge Explainers for the Virtual Keyboard Policy (on our Readme.md). Should we adopt the VK Policy explainer into our repo. Any concerns/objections?

**Comment by johanneswilm** [comment]
Agreed

**Comment by travisleithead** [comment]
Per #321, we don't need to do this, since it's already been incorporated into the VK API spec. 👍
