### ISSUE TITLE
Explore if there are better meeting times for the Web Editing WG

### ISSUE THREAD

**Issue by BoCupp-Microsoft** [w3c/editing#359]
The Web Editing WG [currently meets](https://github.com/w3c/editing#meetings) at 9am Pacific Time on the second Friday each month.  I'd like to make it easier for more geographically distributed people to attend our calls.  We have also had a number of special meetings scheduled recently, which I think is an indicator that maybe we should meet with greater frequency.

Here's a proposal:
* Meet twice a month
* Rotate through three times: one optimized for US / Europe, another for Europe / Japan, and lastly US / Japan

Tagging some regular attendees below to see if there's interest.  Also @masayuki-nakano, @annevk, @smaug----, would you be willing to attend if the meetings were in a better timeslot for you?  Presumably we could get 2 of every 3 meetings inside your normal working hours.

@johanneswilm @snianu @alexkeng @travisleithead @whsieh @comandeer @megangardner 

Anyone interested in the proposal please share your time zones.  I'll start: PDT (UTC - 7)

**Comment by johanneswilm** [comment]
Hey,
the current meetings were set up with the US West Coast and Europe in mind given that most JS editor projects at the time were Europe-based and the browsers US West based. I am Europe-based and I would be open to also attend meetings at 3 am to better suit participants from Asia and US/West. But having a rotating schedule would then also require everyone else to attend meetings in the middle of the night every now and then - else well have to have the same meeting 3 or more times before we can find consensus. Is that something Microsoft's employees would be willing to do @BoCupp-Microsoft ? If that is not possible, and you only attend 2 of every 3 meetings so that we have to take up those points again that Europe/Asia discussed when the US connects, I don't think this would work.

I would be open to meet twice a month, but then those should be meetings filled with really new content and not just the same people stating the same positions over and over again in multiple meetings. I think it may make sense to first try to get better at that and not take up the same items on the agenda again unless there have been some new development.

My time zone is CET (UTC +1).

**Comment by Comandeer** [comment]
My time zone is also CET (UTC+1).

**Comment by BoCupp-Microsoft** [comment]
> But having a rotating schedule would then also require everyone else to attend meetings in the middle of the night every now and then - else we'll have to have the same meeting 3 or more times before we can find consensus. Is that something Microsoft's employees would be willing to do @BoCupp-Microsoft ?

Yes, I'm willing to attend outside normal working hours to avoid the need to repeatedly cover the same content.  My thought is that folks in China or Japan would currently always need to attend outside normal working hours or else not attend at all.  If we adopt a rotation like I suggested then 2 out of every 3 meetings should be inside each member's normal working hours and every third meeting would require attendance outside normal working hours.

This only matters though if we get new attendees.  Currently we just have Europe and US regular attendees, right?  Tagging potential attendees from Japan and China to gauge their interest in this proposal.

@masayuki-nakano @siusin

**Comment by siusin** [comment]
Thanks @BoCupp-Microsoft @johanneswilm !

It'd be easier for me in China if we can move it a bit earlier like 8 am Pacific Time, but I guess it's still difficult for people in the JST time zone. 

@masayuki-nakano wdyt?

**Comment by snianu** [comment]
Tagging few Mozilla folks as well. @annevk @smaug----

**Comment by annevk** [comment]
My timezone is CET. I cannot make midnight meetings, FWIW.

**Comment by masayuki-nakano** [comment]
Oh, sorry, I didn't realize this. My timezone is JST (UTC+9), and I need to leave by 10PM due to legal reason. Additionally, I'm not available at least by end of this year because of some private matter.

**Comment by smaug----** [comment]
My timezone is EET, but I tend to work closer to EST times.

**Comment by BoCupp-Microsoft** [comment]
Providing some more detail on candidate meeting times for us to consider in today's call.  The key changes I'm thinking we should make:

* Rotate through three times: one optimized for US / Europe, another for Europe / Japan, and lastly US / Japan.
* Move meetings to Thursdays instead of Fridays so that the meetings that are not optimized for your timezone don't require you to take away from weekend plans.

Some candidates for US / Europe optimized times would be these:

Seattle | New York | Central European | Tokoyo | Beijing
-- | -- | -- | -- | --
Thu 6:00 am | Thu 9:00 am | Thu 3:00 pm | Thu 11:00 pm | Thu 10:00 pm
Thu 7:00 am | Thu 10:00 am | Thu 4:00 pm | Fri 12:00 midnight | Thu 11:00 pm
Thu 8:00 am | Thu 11:00 am | Thu 5:00 pm | Fri 1:00 am | Fri 12:00 midnight

Some candidates for Europe / Japan optimized times would be these:

Seattle | New York | Central European | Tokoyo | Beijing
-- | -- | -- | -- | --
Thu 9:00 pm | Fri 12:00 midnight | Fri 6:00 am | Fri 2:00 pm | Fri 1:00 pm
Thu 10:00 pm | Fri 1:00 am | Fri 7:00 am | Fri 3:00 pm | Fri 2:00 pm
Thu 11:00 pm | Fri 2:00 am | Fri 8:00 am | Fri 4:00 pm | Fri 3:00 pm
Fri 12:00 midnight | Fri 3:00 am | Fri 9:00 am | Fri 5:00 pm | Fri 4:00 pm

Some candidates for US / Japan optimized times would be these:

Seattle | New York | Central European | Tokoyo | Beijing
-- | -- | -- | -- | --
Thu 1:00 pm | Thu 4:00 pm | Thu 10:00 pm | Fri 6:00 am | Fri 5:00 am
Thu 2:00 pm | Thu 5:00 pm | Thu 11:00 pm | Fri 7:00 am | Fri 6:00 am
Thu 3:00 pm | Thu 6:00 pm | Fri 12:00 midnight | Fri 8:00 am | Fri 7:00 am

I pulled all those time tables [from this site](https://www.timeanddate.com/worldclock/meetingtime.html?month=2&day=10&year=2022&p1=234&p2=179&p3=14&p4=248&p5=33&iv=0) if you want to have a look and put forth others for consideration.

I also created a Doodle with all the candidate meeting times I listed above (it should display for you in your current timezone).  Ignore the date specified in the Doodle; I'm interested in knowing all the meeting times you'd be willing to attend.  Please use [this Doodle link](https://doodle.com/poll/4qbbw72frw4c3x9d?utm_source=poll&utm_medium=link), fill in your name, and check all the boxes for every meeting time that you'd be willing to attend.

**Comment by BoCupp-Microsoft** [comment]
One other thought for today's meeting.  I know we have regular Pacific Time attendees and CET time attendees right now.  At a minimum I'm thinking we should move the meeting to Thursdays and have them start a little earlier (7am or 8am Pacific).  Let's see if we can at least resolve on that in the meeting today and we can more carefully consider rotating meeting times using poll data from the Doodle link above.

**Comment by annevk** [comment]
@BoCupp-Microsoft I think something went wrong with the Doodle. While it claims to show the local times, it appears to be showing the Seattle times for me. Assuming the table above is correct.

**Comment by johanneswilm** [comment]
The doodle seems to work fine for me. It's displaying Oslo time, which is the same as mine.

**Comment by annevk** [comment]
It says it's displaying in Zürich time for me, but the times displayed don't match those of the table in the prior comment.

**Comment by johanneswilm** [comment]
That is true. The table above seems unrelated to the times mentioned in the doodle.

**Comment by travisleithead** [comment]
Follow-up action items:
- [x] update w3c/editing/readme.md with new info
- [x] update [meeting invitation with changes](https://calendar.google.com/event?action=TEMPLATE&tmeid=MDVjYWxldXFiNDhiN3JmMHFqY3FiamRoOTdfMjAyMDEyMTFUMTcwMDAwWiAxN2xtdTNwaHZoamhlaDJpdTljYmppZnI3Y0Bn&tmsrc=17lmu3phvhjheh2iu9cbjifr7c%40group.calendar.google.com&scp=ALL)
- [x] send mail notification out with changes/updates

**Comment by annevk** [comment]
Oh, I thought the meeting was still tomorrow as per https://www.w3.org/groups/wg/webediting/calendar...

**Comment by snianu** [comment]
@annevk we are on google meet right now if you want to join? We'd like to discuss the pickling type proposal and clipboard write permissions.

**Comment by annevk** [comment]
Sorry, I had a conflicting meeting. I can make time next week if you think that would be useful. Will https://www.w3.org/groups/wg/webediting/calendar be updated to be accurate from now on?

**Comment by johanneswilm** [comment]
@annevk I have updated the calendar now.

**Comment by johanneswilm** [comment]
And yes, we will keep that calendar up-to-date from now on.

**Comment by BoCupp-Microsoft** [comment]
I followed up with @alexkeng and he didn't hear back yet from @masayuki-nakano.  I think we can close this issue for now and continue just with our regular 2nd Thursday of the month, 8am Pacific timeslots.  We can revisit if others from a different time zone express interest in regularly attending.
