### ISSUE TITLE
CfC: Publish "EditContext API" as a First Public Working Draft (FPWD)

### ISSUE THREAD

**Issue by johanneswilm** [w3c/editing#366]
This is a public call for consensus to publish the "EditContext API" as a First Public Working Draft (FPWD). As a reminder, the EditContext API: "...is a new API that allows authors to more directly participate in the text input process."

You can view the Editor's draft here: https://w3c.github.io/editing/docs/EditContext/index.html

We will be generating a snapshot from that Editor's draft. If you have an objection to its publication, we kindly ask that you raise it before 10th of December, 2021 by replying below.

Optionally, if you'd like to indicate support please use the 🎉 or 👍  indicators on this issue. You are also welcome to leave comments of encouragement and support for the Editors. Finally, congratulations to the Editors of the specification, who have tirelessly been working on this specification: 

* @alexkeng (Microsoft Corporation)
* @BoCupp-Microsoft  (Microsoft Corporation)

We thank them for their work and dedication to making the Web super!
 
Kind regards, Travis and Johannes (Chairs), and Xiaoqian (Team Contact)

**Comment by travisleithead** [comment]
In my capacity as AC Rep for Microsoft, I'm very happy to support the FPWD for EditContext. This will be a great step forward for editing in the web platform, and I'm very pleased with the editor's work that has gone into the document thus far.

**Comment by travisleithead** [comment]
Note: when we publish, it might be a good time to put the EditContext spec in its own repo (like we did for virtual-keyboard)--see https://github.com/w3c/editing/issues/374

**Comment by siusin** [comment]
This CfC closed with supports.
