### ISSUE TITLE
Each specification in its own repository

### ISSUE THREAD

**Issue by annevk** [w3c/editing#374]
It makes it a lot harder to assess the status of a specification if it's mixed in with all kinds of other specifications. Could this WG please adopt a policy of having one specification per repository, as e.g., W3C WebAppSec, W3C WebApps, and WHATWG also manage things?

**Comment by johanneswilm** [comment]
@annevk We do that once after incubation. Some documents end up just being rough drafts that go nowhere so we don't give them repos at the very start. But I agree that the EditContext API should be moved to its own repository by now.

**Comment by annevk** [comment]
Incubation generally shouldn't happen in WGs. Is incubation somehow in scope for this WG?

**Comment by johanneswilm** [comment]
@annevk In our charter it lists:

"Incubating features related to text editing that may eventually go under the scope of another WG, e.g. Highlight API."

**Comment by annevk** [comment]
I see. FWIW, I'd encourage to have them split from the start. Repositories are rather cheap and for history, blame, and issue triage it's much easier for each draft to have its own repository.

**Comment by siusin** [comment]
Created a repo for EditContext API: 
  https://github.com/w3c/edit-context
([CfC](https://github.com/w3c/editing/issues/366) closed on  14 Dec 2021)

**Comment by travisleithead** [comment]
This is good advice that this WG will continue to apply in the future.
