### ISSUE TITLE
Move to Jitsi for meetings?

### ISSUE THREAD

**Issue by johanneswilm** [w3c/editing#385]
We are currently using Google Meet, and I need to sign attendees in. Can we move to https://meet.jit.si/ or similar? One can start a meeting there and participate without creating an account. For example https://meet.jit.si/W3CEditingCall

@BoCupp-Microsoft You mentioned during today that you are not familiar with it. Could you take a look at it and see if it would work for you? Alternatively, could you make an alternative suggestion?

(cc @travisleithead )

**Comment by BoCupp-Microsoft** [comment]
I'm OK with this tech.  Does it have any limitations that we need to be aware of (like limiting meeting length or limiting number of participants)?

**Comment by BoCupp-Microsoft** [comment]
I'm also OK with trying it out for our Jan. 27th special meeting.

**Comment by johanneswilm** [comment]
OK, let's use on 2022-01-27 then. There is a limit of 100 participants. No other limit that I am aware of. Just in case, we can keep google meet as a backup for the next meeting in case it doesn't work as expected.

**Comment by johanneswilm** [comment]
@travisleithead @BoCupp-Microsoft Our overview page still doesn't mention the meeting on the 27th. Was a time picked for that meeting? If yes, I think we should update the overview page.

**Comment by BoCupp-Microsoft** [comment]
It is scheduled 7:30am-9:00am Pacific Time on the 27th.  I sent an invite to you and others that expressed interest, but I'm happy to have any interested parties attend so we can just put it on our web page along with a Jitsi link.

**Comment by johanneswilm** [comment]
Redundant as #389 has been merged.
