### ISSUE TITLE
CfC to include execCommand to list of possible deliverables

### ISSUE THREAD

**Issue by johanneswilm** [w3c/editing#435]
This is a Call for Consensus to add execCommand to the list of possible deliverables of the 2023 Editing WG charter draft.

See PR here: https://github.com/w3c/editing/pull/434

Discussion: https://github.com/w3c/editing/issues/432

To show support for inclusion, please add a :+1: .

If you'd like to raise a Formal Objection to including execCommand, please do so by using a :-1: by June 27, 2023.
Please include the rationale for your objection as a GitHub comment or email the working group ( public-editing-tf@w3.org ).

If you have other comments or suggestions, please add a comment below.

**Comment by siusin** [comment]
This CfC passes with multiple expressions of support. Thanks!
