### ISSUE TITLE
TPAC 2023 agenda

### ISSUE THREAD

**Issue by johanneswilm** [w3c/editing#438]
The following is a draft agenda for TPAC 2023 on September 14. This agenda can still change. Please contact me in case you want to make changes.

[Minutes](https://docs.google.com/document/d/1PCQL2v8w5Z_bJfjdyu4o7YXPvOPLXhk_MU96c1sOWSU/edit#heading=h.rnhqqju8f8db)

9:30 - 11:00:

 ### Selection handling in Shadow DOM (Tomasz Jakut, CKEditor)

 Sub points will be announced shortly.
 
 ### Delayed Clipboard rendering
 
 - Privacy issue while reading data for web custom types https://github.com/w3c/editing/issues/439
 - What happens to the clipboard data on Tab/Browser Close? https://github.com/w3c/editing/issues/424

11:30 - 13:00:
 ### execCommand/contentEditable

- Define behavior of pressing enter in inline editing host https://github.com/w3c/editing/issues/430
- RFC: Contenteditable "indent" implementations are not aligned with popular editors https://github.com/w3c/editing/issues/437 
- Autocomplete on 'contenteditable' https://github.com/whatwg/html/issues/9065 

14:30 - 16:30: 
 ### UI Events
- Composition event order https://github.com/w3c/uievents/issues/354
- Specify how compositionend works if the caret has been moved to a different element https://github.com/w3c/uievents/issues/5

 ### Input Events

- Adjustments for EditContext https://github.com/w3c/input-events/issues/143

17:00 - 18:30: 
### EditContext

- Secure context for EditContext? https://github.com/w3c/edit-context/issues/11
- Should TextFormat.underlineStyle be an enum? https://github.com/w3c/edit-context/issues/55
- Should attachedElements() return elements that aren't in the DOM? https://github.com/w3c/edit-context/issues/59

**Comment by zcorpan** [comment]
I can attend in person 11:30 - 13:00

**Comment by johanneswilm** [comment]
Connection link: https://w3c.zoom.us/j/3538871864?pwd=S2c1ZmFpYVNDOGk4YjMrZmhOeGROUT09
