### ISSUE TITLE
Linked privacy security doc is for older pickling proposal? 

### ISSUE THREAD

**Issue by caraitto** [w3c/editing#452]
On https://github.com/w3c/editing/blob/gh-pages/docs/clipboard-unsanitized/explainer.md, the linked security-privacy doc is https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/ClipboardPickle/tag-security-privacy.md, which appears to be for the older pickling proposal? Does this also apply for clipboard-unsanitized?

**Comment by snianu** [comment]
@caraitto oops, sorry, forgot to change the link in the explainer. Here is the security-privacy doc for unsanitized read: https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/ClipboardAPI/tag-security-privacy-clipboard-unsanitized-read.md
