### ISSUE TITLE
Upstream changes from trusted types

### ISSUE THREAD

**Issue by lukewarlow** [w3c/editing#461]
This issue is to ask if it would be okay to upstream a change from the trusted types spec. Trusted types are a security mechanism to reduce XSS vulenerabilties, this is achieved via a new API that can allows creation of trusted objects based on policies. Most of the XSS sinks are covered by changing their IDL type to one defined in TT spec which handles all the checks neccessary.

The editing specific section of the spec changes execCommand: https://w3c.github.io/trusted-types/dist/spec/#integration-with-exec-command

**Comment by zcorpan** [comment]
Yes, I think it's OK to upstream.
