### ISSUE TITLE
execCommand has now been spec'd to trigger a "User Intent" for cut/copy/paste

### ISSUE THREAD

**Issue by teleclimber** [w3c/editing#47]
In our discussions it seems we have arrived at the conclusion that in the context of cE=typing, a user triggers an `Intent`, which can be captured by developer as an Event. Developer can then use `execCommand` or something else to perform the intended edit. So the flow, as I understand it is:

```
User Intent => Event Code => custom DOM code or execCommand
```

This is supposed to work for all user edits, like "new line", "delete", etc...

I noticed though that the `cut` `copy` and `paste` events, which are the closest things we have to User Intents in UAs are now triggered by `execCommand`. I think IE has been doing this for a while, but now it's in the spec and implemented in Chrome 43. See http://www.w3.org/TR/2015/WD-clipboard-apis-20150421/#the-copy-action

I made this Fiddle that demonstrates a minimal implementation:
http://jsfiddle.net/teleclimber/y5xqtbL2/

So you can see now the pattern is:

```
execCommand => Event Code => allow event to continue or preventDefault and do custom work
```

This is completely backwards from the way we want to do things. This may not be a huge deal, but it would be weird if developers had to use `Intents` for everything except clipboard ops where they have to use `execCommand`. It's inconsistent.

PS: With respect to #33 if execCommand are spec'd to do nothing, does that mean they don't fire events either?

**Comment by johanneswilm** [comment]
#33 ended with execCommand not being defined for cE=typing, in the expectation that execCommand behavior will be specified independently of cE, AFAICT.
The intent events you mention sound as if they shouldn't be the same intent events we need in cE=typing. But maybe you would like to start to spec execCommand? Should we open a new document for that?

**Comment by johanneswilm** [comment]
@hallvors Hey, we should probably coordiante about this.

**Comment by johanneswilm** [comment]
@fredck @hallvors You should look at this as well.

Basically, we need to have some coordination of execCommand. We cannot both say that:

> If an implementation supports the document.execCommand method and allows calling it with the commands "cut", "copy" and "paste", the implementation must trigger the corresponding action, which again will dispatch the associated clipboard event.

and

> In other words, execCommand should not be a feature of cE, but a document feature... and sincerely, it should not dependent on cE at all... it should just take the current selection and execute the requested command on it, period. (I mean, even in non cE selections)

If we also want cE=typing to work with user intents in which we want the site to be able to control what action is triggered upon user intents (or no action at all if no action is defined).

@hallvors How about we specify that the things mentioned in the clipboard api in relation to editable elements are only true for designMode and the current contentEditable, but not contentEditable=typing? Where would we need to discuss that?

**Comment by teleclimber** [comment]
> The intent events you mention sound as if they shouldn't be the same intent events we need in cE=typing. 

I'm not sure I follow that. I assumed we would have `Intent` or `Device Independent Events` or whatever we call them for clipboard ops.

I definitely, most positively, assuredly, completely do NOT want to try to spec `execCommand` thank-you very much!

**Comment by johanneswilm** [comment]
:) OK understood. But it seems that others have started spec'ing parts of it in other places (such as the clipboard spec), so we'll have to coordinate with that.

**Comment by johanneswilm** [comment]
> I'm not sure I follow that. I assumed we would have Intent or Device Independent Events or whatever we call them for clipboard ops.

All I meant is that the event that is triggered after the DOM has changed because a paste has taken place already through execCommans should not be the `Intent Event` we want to listen to before paste takes place.  We need to clarify that within cE=typing, there should not be a forced change fo the DOM due to user action.

**Comment by teleclimber** [comment]
> the event that is triggered after the DOM has changed because a paste has taken place already through execCommans should not be the Intent Event we want to listen to

Yeah but that's the thing. The "paste" event fires **before** the DOM is changed. And through this event we can set the custom behavior of paste. Exactly as you would for an intent event.

So yes, we definitely have to coordinate to avoid conflicts and also to avoid having too many different ways of doing one thing.

**Comment by hallvors** [comment]
Hi, to be honest I'm not well informed about what you are working on here. But it seems like you insert a new sort of event handling ('intents') into the process of editing text, and then sort of re-use execCommand() with new actions like "new line", "delete"?

Why are you re-using execCommand() if you don't even want to spec it completely?

From the perspective of the clipboard events spec, it doesn't matter at all whether designMode or contentEditable is enabled. If you run document.execCommand('copy') without either, per spec the copy event must fire. No selection? It still fires. 

And yes, the copy/cut/paste events seem quite close to your "intents". Is it possible to trigger such intents from, say, an HTML BUTTON element?

**Comment by johanneswilm** [comment]
@hallvors No, we would of course need to spec the execCommands if we were to depend on them. We are just creating a new way of editing text (just allow text insertion into text nodes and moving the caret) and everything else will have to be handled via Javascript -- whcih then again can choose to use execCommand for some things, should that be available, but could also just manipulate the DOM through javascript directly.
So according to this plan, there will be an intermediate step between the user showing an intent and the browser response to that. If no piece of JavaScript is listening for a specific intent event, nothing will happen. This seems to go against the clipboard spec which seems to say that paste will take place within an editable environment, unless it's cancelled with preventDefault, correct?

The "intent events" we are defining here should be related to text input inside of cE=typing. If you want to create a button for for example, creating a new line, you can simply listen for the button click and then execute the same function you have associated with the "new line intent".

**Comment by hallvors** [comment]
Thanks for the explanations :) Here's one suggestion: when defining the paste action, I've written

```
If there is a selection or cursor in an editable context
```

and I could change that to say 

```
If there is a selection or cursor in an editable context where pasting is enabled
```

and in your spec you simply say something about pasting not being enabled and scripts having to listen for the beforepaste event if they want to enable the "paste" commands in the UI, and to the paste event in order to handle and insert data. Sounds good?

**Comment by johanneswilm** [comment]
Yes, that sounds reasonable. I will add that to the spec.

**Comment by hallvors** [comment]
And the clipboard events change landed here: https://github.com/w3c/clipboard-apis/commit/1aad4cec80b119d872de083cfc0c12ce927c7886
