### ISSUE TITLE
CfC: Enable automated publication system for all Web Editing WG specs

### ISSUE THREAD

**Issue by johanneswilm** [w3c/editing#471]
Hey,

this is a CfC for enabling the automatic publication system of the W3C for all Web Editing WG specs that have reached First Public Working Draft (FPWD) or higher.

This group decision will cover possible future specs adopted by the group under its current or possible future Charter.

This change is to facilitate more timely w3.org/TR updates and to make editors' day-to-day work more frictionless.

If you have comments or questions or you disagree with this decision, please comment on this Github issue by October 10 2024.

Best regards,

Johannes Wilm (IE, Web Editing WG Chair)

**Comment by siusin** [comment]
This CfC has closed with no objections. Thank you.
