### ISSUE TITLE
What intentions do we need?

### ISSUE THREAD

**Issue by johanneswilm** [w3c/editing#52]
We currently have 
- insertCharacter
- overwriteCharacter
- replaceText
- insertNewline
- deleteContent
- undo
- redo
- caretUp
- caretDown
- caretRight
- caretLeft
- caretStartLine
- caretEndLine
- caretStartPreviousWord
- caretEndNextWord
- ~~setInsertCaret~~
- ~~setOverwriteCaret~~

cut and paste should be handled through ~~beforecut and beforepaste~~ cut and paste events. Anything else?

**Comment by ctalau** [comment]
To my understanding, the spec [1] implies that beforecut and beforepaste events may trigger even if the paste action is not performed by the user. 

> Typically, the before\* events fire before a menu is shown to the user, or when the user presses a combination of shortcut keys that would trigger a clipboard command. The user agent is explicitly allowed to fire these events at any time. If the UI has visible buttons that trigger clipboard actions, the implementation may want to fire these events at regular intervals to keep the state of these buttons updated.

Instead, we need an intention that is triggered only when the user actually performs the cut or paste action.

[1] http://www.w3.org/TR/clipboard-apis/#events

**Comment by johanneswilm** [comment]
Yes, that wording sounds very strange. @hallvors could you explain what is going on there? Do we need extra events for when cut and paste really happen?

**Comment by hallvors** [comment]
That would be the "cut" event and the "paste" event, no? For your purposes you I think you can just ignore the before\* events in the clipboard spec. They are a semi-weird solution for the use case "let the browser know if the web page can handle a cut/copy/paste action".

**Comment by johanneswilm** [comment]
@hallvors ok, so we can listen for cut/paste events without being forced to actually execute either one? That sounds fine.

**Comment by hallvors** [comment]
Per the discussion in another editing-explainer thread (I apologise for not looking it up right now) you decided to say that pasting/cutting was not "enabled" in a cE=typing context. This means per the modified clipboard spec that the cut/paste events will fire, but by default nothing whatsoever will happen. The script will have to listen for the event and do things manually if desired.

**Comment by ctalau** [comment]
@johanneswilm @hallvors ok, that's fine for cut/paste.

There are some input methods that allow the user to change the selection which do not fall into any categories mentioned above:
- select word - e.g on iOS long touch on a word and choosing _Select_ from the menu.
- select all - e.g. Ctrl + A
- select block - e.g. triple click on Windows
- caret page up
- caret page down

The first three can be specified to do nothing on the UA side and to be implemented in JS. However, the last two are more complex to handle in JS.

**Comment by johanneswilm** [comment]
@ctalau: If we should define default behavior for caret page up/down, what would you expect it does?

**Comment by ctalau** [comment]
I don't think they would need a default behavior. AFAIU the whole idea with intentions is not to have default behavior. 

The problem is similar with the one about caret movement in block direction discussed in issue #56. So, we need an event without a default behavior and some mechanism provided by the UA to move the caret using script.

**Comment by johanneswilm** [comment]
@ctalau Yes, it's easy enough to create another intent without default behavior. But you mentioned "However, the last two are more complex to handle in JS." So what would you want/need extra to be able to handle them? 

The latest additions to the discussion mean that we will likely again have default behavior of the arrow keys, and also the intents as described above. So for page-up-page-down we could either do that or not get any default behavior either.

**Comment by ctalau** [comment]
I think we should treat them exactly like caret-up/down.

**Comment by johanneswilm** [comment]
So by default they will go one line up or down?

**Comment by ctalau** [comment]
I meant that they should have a default behavior if and only if the caret-up/down have one.

**Comment by johanneswilm** [comment]
Ok, yes. But what would you need to do it manually
