### ISSUE TITLE
What to do with IME input when typing over a large selection?

### ISSUE THREAD

**Issue by johanneswilm** [w3c/editing#59]
Imagine this:

```
<div contentEditable="typing">
  <p>This is a test <span>t[ext</span></p>
  <p>This is a <b>secon]d paragraph</b></p>
</div>
```

The []-symbols mark the start and the end of a selection. With this selection in place, the user now starts creating new input using IME. What do we do?

We specifically tried to avoid for the UA to do paragraph merging or any changes to the DOM-structure. and the IME added characters will only create a beforeInput (intention) event, not an actual insertion by default. 

Solutions I can see:

A) If the IME is to overwrite anything beyond the contents of a simple text node, the composition process is not done inline but rather in a little box next to the text.
B) We first emit a beforeInput delete event, then start the composition process.
C) IME handling is moved further to Javascript.

I vote for B.

**Comment by rniwa** [comment]
I agree B is the only acceptable option here.

**Comment by johanneswilm** [comment]
@rniwa: I guess we need to say something about how this will work in terms of timing or callbacks or something. Basically we need something like:
1. User types a key indicating the start of a composition process.
2. beforeInput delete event is emitted by UA
3. JS code handles deletion request and when it has finished that, it places the caret where the IME input is to be inserted.
4. UA handles IME composition
5. beforeInput insertCharacter events are emitted by UA
6. JS code handles insertion of characters.

My concern is about the transition from 3 to 4: How does the UA know that 3 has terminated and that it can now go on with 4?

**Comment by rniwa** [comment]
Step 3 needs to happen synchronously within an event listener/handler of beforeInput/input event fired in step 2.

**Comment by johanneswilm** [comment]
yes, step 3 happens because the JS code listened to the event emitted in 2.

Also the other steps should work without problem: 1 leads to 2, 2 leads to 3, 4 leads to 5, 5 leads to 6.

Just the connection of how 3 and 4 are connected are somewhat blurry to me.

**Comment by rniwa** [comment]
I mean... as far as the spec is concerned, we'd check if the default action of the event we fired in 2 has been canceled or not.  If it has not, then proceed with accepting composition text.  If it has, clear the composition.

**Comment by johanneswilm** [comment]
But the default action for all of the editing events within conententEditable=Typing is "None". So by default there is no preventDefault() employed for any of these. By default, nothing ever happens. It's only when a specific event is handled in JS that it will actually cause a change.

And is it unproblematic for you that you don't know how long time the JS code will spend on doing the proper deletion before the insertion can start? The deletion process will likely involve moving the caret to  a specific place where the composition then should start.

Sorry if I misunderstood you.

**Comment by rniwa** [comment]
It's bad if JS spends a lot of time doing anything since Web is single threaded but I don't think we want to come up with an ad hoc solution just for editing.

Now, I don't think we should make the default selection behavior to do nothing.  The reason we can do nothing in other editing actions is that UAs don't typically allow editing of arbitrary text in regular non-editable parts of the page.  Such is not the case with selection.  UAs typically allow users to select any part of the page so disallowing that inside contentEditable=typing will be going against the norm.

Also, the original idea of contenteditable=typing was to allow caret movement and editing of text nodes so I don't know where you got the idea that we would also be disallowing caret movement by default.

**Comment by johanneswilm** [comment]
> Now, I don't think we should make the default selection behavior to do nothing. The reason we can do nothing in other editing actions is that UAs don't typically allow editing of arbitrary text in regular non-editable parts of the page. Such is not the case with selection. UAs typically allow users to select any part of the page so disallowing that inside contentEditable=typing will be going against the norm.

I am not sure I follow you. The selection was already done before all of this (call it point 0). This is all about how to handle the situation in which a large part of content is selected already and the user starts IME composition. Are the points I listed above not clear?

**Comment by rniwa** [comment]
Ah I misunderstood. Anyhow, I don't think there is any ambiguous here.  UA just issues a request to delete the selected region, then issues another request to start composition.  That's all there is to it.
