### ISSUE TITLE
Definitions of inline and block elements are imprecise

### ISSUE THREAD

**Issue by rniwa** [w3c/editing#67]
They should be referring to the concept of the [used value](http://www.w3.org/TR/css-cascade-3/#used) in CSS3.

**Comment by kojiishi** [comment]
What about other values such as inline-block or Ruby?

**Comment by johanneswilm** [comment]
Should we add inline-block to inline-elements as elements where the caret needs to be able to be before and after?

**Comment by johanneswilm** [comment]
As for ruby -- You all know this better than me, but I would imagine that at least ruby base or ruby containers should be treated like inline elements? Or what do you think @rniwa @kojiishi ?
