### ISSUE TITLE
Should the term be Device Independent Events?

### ISSUE THREAD

**Issue by BenjamP** [w3c/editing#7]

**Comment by rniwa** [comment]
I think "intentions" is a confusing name because of "Web Intent" the WebApps working group worked on in the past.  To diffuse the confusion, we should probably stick to "command" or some other noun not associated with another specification.

**Comment by BenjamP** [comment]
Can you elaborate on those? Command was discussed with the <menu> element, so that's not much better. I think Intention captures the real meaning here. As mentioned in the Intentions Spec:

Definitions:
Action: any way a user interacts with a webpage, including click, type, touch, and gesture
Intention: what a user is trying to do by performing an action, including select, undo, insert text, and delete
Behavior: the result of an intention being fulfilled, including feedback to the user or service

**Comment by BenjamP** [comment]
Also "Command" is a design pattern that we're not really using here.

**Comment by BenjamP** [comment]
Another option is to use "Action Event", referring to the Action that a browser or site might take.

**Comment by KenjiBaheux** [comment]
I agree that intention as in "user's intention" captures what the spec is after. Perhaps it's too broad though and it might be seed as covering any kind of intention (hence the potential confusion with Web Intents).

An "Action Event" sounds like the event you would get when an Action has been performed (which is precisely the case in the current spec IINM.)

Do we need an alternative or would a unambiguous framing do the trick?

Alternatives: 
- Desire as in a user's desire?
- Motive as in the "action speaks nothing without the motive" fortune cookie ;)

Framing:
- Editing intent event?

Both combined:
- Editing desire event ?
- Action motive event?

**Comment by BenjamP** [comment]
I think it's fine if it's broad. If this concept works well for Selection and Editing, it could potentially be expanded to other areas. The events themselves will be more specific (beforeSelectionChange, beforeInput), but the concept is general in my opinion.
Reposting my thought from the Task Force mailing list: The question really is should the events be the "Intention" of the user, the "Action" of the browser/site, or the "Command" itself?

**Comment by rniwa** [comment]
In my mental model, I'm issuing a command to bold text when I'm bolding text.  Imagine a case where I have partially bolded text and I have an intention to unbold it.  As an user, I can either issue a single command that unbolds text.  Alternatively, if "bold" command toggles the bold-ness of text, then I might want to bold the entire text first, and then issue the same command again to unbold the entire thing.

So users may have an intention to do something but his/her intentions will manifest in the form of multiple concrete commands or user actions to achieve that.

**Comment by BenjamP** [comment]
Responsive Input seems to be winning here.

**Comment by BenjamP** [comment]
Now Device Independent Events is the forerunner. Straightforward!

**Comment by BenjamP** [comment]
Any arguments with Device Independent Events?

**Comment by rniwa** [comment]
We like "Device Independent Events".
