### ISSUE TITLE
should not use the shadow DOM for beforeInput

### ISSUE THREAD

**Issue by ojanvafai** [w3c/editing#76]
As discussed at the F2F, we're moving the ce=events spec to ce=typing and will not specify that the DOM is not modified during IME input. Instead, authors can today move the selection to a different element to get the composition inserted there.

See http://jsbin.com/pubeqanefe/1/edit?html,output for an example of moving the selection. This needs more thorough testing. It works in Chrome on Mac at least. We should make sure it works in all browsers/platforms. If not, I expect this is a bug we can get fixed.

**Comment by johanneswilm** [comment]
This shows an example how the composition can be made to happen in a different element, and when done the composed characters are put back into the main document. This works in Chrome, but not (without modifications) on Firefox.

**Comment by johanneswilm** [comment]
This shows an example how the composition can be made to happen in a different element, and when done the composed characters are put back into the main document. This works in Chrome, but not (without modifications) on Firefox.

http://jsbin.com/heyudoguse/edit?html,js,output

**Comment by johanneswilm** [comment]
This version works in Chrome and Firefox, which work somewhat differently. FF requires the JS to move the characters back, Chrome doesn't. The Chrome behavior requires less intervention by JS.

http://jsbin.com/sivunehesi/1/edit?html,js,output

**Comment by johanneswilm** [comment]
Here, this is is using Shadow DOM and works in Chrome: http://jsbin.com/yutakuroju/1/edit?html,js,output

**Comment by johanneswilm** [comment]
Updated examples:

One that works in FF and Chrome: http://jsbin.com/jetoqezuho/1/edit?html,js,output

One that works in Chrome and uses Shadow DOM and does inline editing: http://jsbin.com/fudeqikivu/1/edit?html,js,output

**Comment by johanneswilm** [comment]
FTR: It turned out that a recent windows IME doesn't allow moving the caret during composition.

**Comment by johanneswilm** [comment]
Closing this as text about SHadow DOM/IME has been removed from text.
