### ISSUE TITLE
Can composition contain element boundaries?

### ISSUE THREAD

**Issue by kojiishi** [w3c/editing#77]
I'm not sure if this question was raised and resolved before, but I've got a use case to share for a discussion.
1. A word in a document `<b>A</b>pple`.
2. Tap between two `p`s.
3. When the caret is set, Android puts the whole word into a composition, so the bold part is gone in the rendering.

Would be nice to render elements within the composition in this use case.

**Comment by johanneswilm** [comment]
@kojiishi We learned yesterday that all input on Android is IME, and that IMEs have very different interfaces that we cannot standardize at this stage. Are you suggesting for this to be a feature of a future standardized IME interface?

**Comment by kojiishi** [comment]
No, I just want to make sure composition can contain element boundaries, since there were some discussions that do not allow this before. If it's already assumed, that's fine, sorry about a noise.

The issue is about so-called "re-conversion" that turns committed text back to composition. Most IME I know have this feature, but Android kicks this feature just by a tap, so it's more obvious.

**Comment by johanneswilm** [comment]
You mean the issue about spellchecking across element boundaries? Yes, that was resolved by browsers getting their way, and more complex editors turning spellchecking off as a consequence ;-).

Reopen if you feel this has not been covered.

**Comment by ojanvafai** [comment]
Do you have a pointer to that other discussion? I'm not disagreeing with this resolution, just want to understand what went into it.

**Comment by johanneswilm** [comment]
Here: https://github.com/w3c/editing/issues/50 This is the second part of it. Earlier it was made clear by Safari that they cannot give access to the spellchecking directly, because for them that is a security concern.
