### ISSUE TITLE
RESOLUTION: We are going to focus on describing ce=typing as a priority.

### ISSUE THREAD

**Issue by johanneswilm** [w3c/editing#85]
The current documents describing "new" behavior will be merged, and there will be markers on all other levels of the doc specifying that the specifics of those levels are to be specced in the future.

**Comment by fredck** [comment]
Not having participated in the F2F, what you said sounds unclear.

Do you mean that "typing" will be spec'ed first and "caret" and "events" later on? Is this anyhow possible considering that one depends on the other?

**Comment by johanneswilm** [comment]
Yes, the reason being that Chrome is concerned about that IME handling through the Shadow DOM may be a performance concern for them. Instead we found out ways in which we allow JS to move the caret and do all that by itself.

At the time when cE=caret will be specced, in X years, the JS will have direct access to all the internals of IME character construction. For now we start with Typing, which then also should be the first one to be shipped.

**Comment by fredck** [comment]
You've been talking about "subsets" where `typing = events + caret + X (typing specific stuff)`. So you're spec'ing "X" only, then typing will not be spec'ed, just a fraction of it.

Really, you don't have to convince me. I'm fine with the resolutions taken at the F2F meeting. Still this is very unclear for me. But anyway, you don't have to explain it again. Just wanted to leave my understanding of this documented. I'm sure this will be clear when the spec will be in place.

**Comment by johanneswilm** [comment]
Technically, you are right that cE=typing probably also should have the direct IME-access. But given we are in a situation where we finally have a compromise after 10-15 years of chaos, I think we are much better off allowing for some mild inconsistency in this first version of the spec. The point is that cE=typing, once implemented, will be directly usable, whereas the lower levels won't due to the lack of IME support. Once we spec cE=events with access to the inner workings of IME in a few years, we should also get access to that in cE=typing.

I am afraid we have to choose between either taking the deal as offered by browser makers, or just forget about it.

**Comment by Reinmar** [comment]
I think that the deal is really great. After few hours of the meeting it became really clear that it's the only option, but we were able to find a way to make it totally controllable for the editor developers. For instance, interaction of IME with a document will happen via firing events which will have default actions, but which will be "adjustable". Taken that we also removed selection normalisation we are really fine here.

And one more thing – the inconsistencies will happen in the `caret - events` fraction (**which makes no DOM modifications**). The `events` part is clear and the `typing` part is also clear. We just found that `events` and `caret` are not yet sufficient today to build your own editor, as all variants of IMEs cannot be exposed easily to editor developers. But even not exposed, they can fire events consistently.

**Comment by johanneswilm** [comment]
Yes, I also think it's good for everyone involved -- it gives us a) full usability right from the start and b) full consistency and atomic access to all relevant parts of text input/manipulation with time. It just doesn't give us c) full consistency and atomic access to everything immediately. And I think that is OK.

**Comment by johanneswilm** [comment]
This should be clear now.
