### ISSUE TITLE
change of event names beforeInput -> beforeEdit -> beforeInput?

### ISSUE THREAD

**Issue by johanneswilm** [w3c/editing#87]
At the F2F we talked about the name of the events we are going to fire beforeInput/Input:  http://www.w3.org/2015/08/24-webapps-minutes.html . 

"RESOLUTION: remove caret, and put it in beforeselectionchange in selection API
... We call the relevant events edit and beforeedit (instead of overloading input)"

However, we now find that @ojanvafai disagrees with that change: https://github.com/w3c/editing/issues/73#issuecomment-135037793

Also, I found that the reason we only found a number of broken links to the event in other specs is that the Input event was removed from other specs because it was now specified in our spec.

Some more things I discovered: 
- The beforeInput event is actually mentioned in several other specs. For example here: https://w3c.github.io/uievents/#h-sync-async or https://w3c.github.io/uievents/#h-events-keyboard-event-order but with a broken link. It is described as synchronous (correctly) and I also think it describes correctly the order of events.
- At above links the beforeInput event is described as "only for keys which produce a character value". I don't think that corresponds to how we want to use that event with formatting bold, etc..
- Here it describes the InputEvent: https://developer.mozilla.org/en-US/docs/Web/API/InputEvent but the link to the specification gives us another dead link. I can see that the event was removed from that spec in January: https://github.com/w3c/uievents/commit/b2bd0cfea66b00a0fc7f25993716a3374db90beb due to a bug report by Gary Kacmarcik (Google) https://lists.w3.org/Archives/Public/www-dom/2015JanMar/0029.html because it was now covered by our spec.

.... so altogether it seems as if the beforeInput/Input events mentioned other places are earlier versions of the event we have been describing in this spec until it changed name due to the decisions of the F2F.

Testing it out on Chrome and FF, it doesn't look like the input event on cE=true elements holds any information.

**Comment by johanneswilm** [comment]
The one thing that would need to be changed in the "UI Events Specification" no matter which name we give the event is that it says that the beforeInput event is "only for keys which produce a character value" [1]. I spoke to @ojanvafai at the CSSWG meeting about this, and he said it was an error in that document, because they probably exchanged the "textinput" event with the "beforeinput" event and then left that text in there by mistake.

[1] https://w3c.github.io/uievents/#h-events-keyboard-event-order

**Comment by travisleithead** [comment]
That is very likely the case. Care to file an issue on the UI Events spec for us to address this?

**Comment by johanneswilm** [comment]
Another issue with this potential name change: The beforeInput/Input event will be triggered also on Input fields and textareas. These fields do not have selections that can be expressed as ranges. For most edit types this shouldn't matter, because the taregtRanges will be null anyway. But in the case that one would expect target ranges (fx, when using the spell checker in a textarea), this will be an issue.

I consulted @ojanvafai briefly about this, and he suggested to just let the targetRange always be null in the case of textareas and input fields. 

See also https://github.com/w3c/editing/issues/80

**Comment by masayuki-nakano** [comment]
Do you make input event deprecated? The input event is used by a lot of websites. It doesn't make sense to completely drop input event from the spec. At least, it should be documented as a legacy event. Firefox already supports InputEvent.isComposing attribute.
https://developer.mozilla.org/en-US/docs/Web/Events/input

**Comment by johanneswilm** [comment]
@masayuki-nakano we tried it out during the F2F, and I believe we found Firefox on Mac OS X on one laptop would fire the input event on contenteditable, while the same code and the same version of Firefox would not fire on another Mac OS X laptop. The event seemed unreliable, which was also a contributing factor in us not wanting to mess with it.

However, we were not aware that the definition of the event was in our ED spec only so that changing the name of the event would deprecate it. 

We are now waiting for Apple and Google to come to an agreement on this.

**Comment by masayuki-nakano** [comment]
> while the same code and the same version of Firefox would not fire on another Mac OS X laptop.

If so, it's a bug of Firefox. But if it's really existing, Firefox's many features are broken, e.g., incremental search in various UI, autocomplete in form fields. So, I cannot believe there is such odd bug unless I see some bug reports with STR.

> The event seemed unreliable, which was also a contributing factor in us not wanting to mess with it.

input event is the only way to handle something immediately after text is modified in an editor at least for now. Therefore, it must be used in a lot of websites.

Therefore, even if some spec will define input event as deprecated, browsers keep supporting it for compatibility.

**Comment by johanneswilm** [comment]
I am just saying how things happened at the meeting and what our state of information was at the moment. I don't think anyone wanted to deprecate Input events, especially for <input> and <textarea>. This was merely about a new <contenteditable=[X]> for which we were about to define events.

If Apple and Google come to the agreement that they want to keep the beforeEdit and Edit events, I believe we will have to put the Input event for <input> and <textarea> back into uievents. contenteditable=true is not specced anyway, so it can keep the event without that causing a spec problem, so it can keep the event without causing a spec problem.

**Comment by ojanvafai** [comment]
Removing "input" from contentEditable=true is not an option. There is a lot of content that depends on it.

The two options that are being considered are:
A. Fire beforeEdit/edit/input on all contentEditable elements and only fire input on textarea/input elements.
B. Fire beforeInput/input on all contentEditabe, textarea and input elements.

I feel strongly that we should do (B) since we already have the "input" event. I stated the detailed reasons in issue #73, but I'll summarize:
1. We should not have two events that are entirely redundant except for the fields on them ("edit" and "input"). This is both confusing for developers and has unnecessary performance overhead since some pages would have event handlers for both events.
2. We should not have different events for contentEditable/textarea/input. Conceptually, textarea/input should be a contentEditable inside a closed shadow DOM. In that world, some fields won't make sense (e.g. targetRanges) and will need to be null and some editTypes will simply never fire (e.g. ctrl+b won't fire an event because they are plain text). That's OK IMO.

@rniwa does option (B) sound OK to you?

**Comment by masayuki-nakano** [comment]
> Removing "input" from contentEditable=true is not an option. There is a lot of content that depends on it.

I agree with this.

> The two options that are being considered are:
> A. Fire beforeEdit/edit/input on all contentEditable elements and only fire input on textarea/input elements.
> B. Fire beforeInput/input on all contentEditabe, textarea and input elements.

I think that (B) must be the best choice for backward compatibility. As I said above, browser cannot get rid of input event, anyway. So, even if it's defined as "shouldn't be fired on XXX", browsers cannot do that for keeping compatibility with existing websites.

**Comment by johanneswilm** [comment]
> The two options that are being considered are:
> A. Fire beforeEdit/edit/input on all contentEditable elements and only fire input on textarea/input elements.
> B. Fire beforeInput/input on all contentEditabe, textarea and input elements.

well, and

C. Fire beforeEdit/Edit on contenteditable=[X] and input on textarea, input and cE=true as long as cE=true implementations don't follow any spec anyway.

This should not break any content. Once cE=true behavior changes (to follow a spec), it will break the web anyway.

That being said, I don't mind changing it back to beforeInput/Input is everyone agrees with that. The problem is that we currently have a resolution to have these other names, so unless we all agree to sidestep that resolution, the names are what they are (beforeEdit/Edit).

**Comment by gked** [comment]
There is an Input event fired in MS Edge. I wouldn't argue the name change except for making a small clarification. BeforeInput/Input events should be Cancellable, correct? If this is the case, then I would have to change at least that part in  Edge as currently, Input event is not cancellable. I am curios, if the event is cancellable in Firefox? My point is that how much of Input behavior will need to be changed?

**Comment by johanneswilm** [comment]
@gked: I don't think we need to make the Input event cancellable. What needs to be cancellable is the beforeInput or beforeEdit event -- except if it is triggered due a composition. If the user is inside a composition process, the consensus among the browser makers at the F2F seemed to be that it is impossible to cancel due to the technical limitations of IMEs, which won't allow cancelation.

The spec has been updated since the F2F to take this into consideration.

**Comment by gked** [comment]
makes sense.
