### ISSUE TITLE
The web doesn't need another badly implemented API

### ISSUE THREAD

**Issue by mightyiam** [w3c/editing#88]
Excuse me for raising a voice that goes against the entirety of what you're gathering here to do, but I must say what I feel is the truth.

There is no need for such an API. I feel that the `contentEditable` stuff should just be deprecated.

For two reasons:
1. There is no way that browsers will implement such a complex API in a reasonably consistent manner.
2. It is possible to write client code that implements all of this, without using any `contentEditable` at all.

**Comment by johanneswilm** [comment]
Hey, I will close this as it seems likely you are trolling. Please go to the mailing list if you are not.
