### ISSUE TITLE
Broken links make documentation useless

### ISSUE THREAD

**Issue by IanKemp** [w3c/editing#90]
http://www.w3.org/TR/DOM-Level-3-Events/#event-types-list

Check the target of  "input" in the table. Notice how it points to an anchor. Now click the link. Notice how you aren't taken to an anchor. Notice how the document you're taken to doesn't even mention the input event.

In the document you're taken to (https://w3c.github.io/editing/input-events.html), click the link at the top of the document below the "Latest published version:" text. Notice how this link takes you to an error 404 page.

This is not the first time I've encountered broken links on the W3C website, and I'm sure it won't be the last. For guys who are supposed to be custodians of the web, you're pretty terrible at making your own pages not break.

**Comment by AFBarstow** [comment]
This Issue has been copied/duplicated as https://github.com/w3c/uievents/issues/53 thus I am closing it now.

@garykac @travisleithead
