### ISSUE TITLE
We need a new static range API

### ISSUE THREAD

**Issue by rniwa** [w3c/editing#91]
For `beforeInput` and `input` events, we need a static Range-like object.

**Comment by gked** [comment]
I am sorry guys, the connection was pretty bad, I couldn't hear you very well and you didn't hear me at all. 
Could you please elaborate as to why it should be static and are we going to scope it down to all editing types?
thank you
--grisha

**Comment by rniwa** [comment]
So Ojan (and the rest of Blink folks) don't want to have a new API that uses live Range objects because they impose runtime cost in other DOM APIs (removing nodes, etc...).

**Comment by johanneswilm** [comment]
This seems to be covered by https://discourse.wicg.io/t/proposal-staticrange-to-be-used-instead-of-range-for-new-apis/1472
