### ISSUE TITLE
Selection API - difference between collpase() and setPosition

### ISSUE THREAD

**Issue by glyukshin** [w3c/editing#94]
Hi All,

I am sorry if this question has been asked before.

I was going through Selection API https://w3c.github.io/selection-api/#widl-Selection-collapse-void-Node-node-unsigned-long-offset and came across these two functions collapse() and setPosition(). From what I can tell, they are identical in what they do.

Question:
It looks like it was added in this past year. Why was it added?

It seems redundant, unless I am missing something

**Comment by rniwa** [comment]
They were added for the Web compatibility.  See https://github.com/w3c/selection-api/issues/38

**Comment by rniwa** [comment]
Closing this issue. Please re-open the issue if you find this response unsatisfactory.
