### ISSUE TITLE
Base definition and ordering of beforeInput/input events should be in UI events, but the editing specific stuff should be in a separate editing spec.

### ISSUE THREAD

**Issue by gked** [w3c/editing#99]

**Comment by johanneswilm** [comment]
Ok, should we go ahead with this? Will you add the needed things in the UI events spec and then I delete them here, or should we do it the other way round?

**Comment by garykac** [comment]
UIEvents has already been reverted (to re-add the content that was removed), so remove it from Editing whenever you want.

**Comment by johanneswilm** [comment]
@garykac It should now be removed here. But which version of the UI events spec has it been added to? In those I found [1] [2], I didn't see it.

[1] https://www.w3.org/TR/uievents/
[2] https://w3c.github.io/uievents/

**Comment by garykac** [comment]
They're in [2].

I added them back on Jan 8:
https://github.com/w3c/uievents/commit/846c78a9a5c4b3a868ed8654ddd04ef17e92f5ab

But curiously I they didn't appear until just now when I sync'ed and
resolved conflicts with some Jan 19 changes. Odd.

Anyway, thanks for pointing that out. Everything should be fixed now.
